### ISSUE TITLE
Audio error running astroblasto: hardware params could not be set

### ISSUE THREAD

**Issue by freiguy1** [ggez/ggez#102]
Hello there. Grabbed latest just trying the framework for the first time. When running astroblasto, I get an error, here's the backtrace:

```
Welcome to ASTROBLASTO!

How to play:
L/R arrow keys rotate your ship, up thrusts, space bar fires

thread 'main' panicked at 'hardware params could not be set: "Invalid argument"', /checkout/src/libcore/result.rs:859
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:60
             at /checkout/src/libstd/panicking.rs:355
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:371
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:549
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:511
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:495
   7: rust_begin_unwind
             at /checkout/src/libstd/panicking.rs:471
   8: core::panicking::panic_fmt
             at /checkout/src/libcore/panicking.rs:69
   9: core::result::unwrap_failed
             at /checkout/src/libcore/macros.rs:29
  10: <core::result::Result<T, E>>::expect
             at /checkout/src/libcore/result.rs:761
  11: cpal::cpal_impl::Voice::new
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/cpal-0.4.5/src/alsa/mod.rs:577
  12: cpal::Voice::new
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/cpal-0.4.5/src/lib.rs:338
  13: rodio::engine::new_voice
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/rodio-0.5.1/src/engine.rs:135
  14: rodio::engine::Engine::start
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/rodio-0.5.1/src/engine.rs:76
  15: rodio::engine::play_raw
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/rodio-0.5.1/src/engine.rs:50
  16: rodio::sink::Sink::new
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/rodio-0.5.1/src/sink.rs:35
  17: ggez::audio::Source::from_data
             at /home/user/temp/ggez/src/audio.rs:106
  18: ggez::audio::Source::new
             at /home/user/temp/ggez/src/audio.rs:101
  19: astroblasto::Assets::new
             at /home/user/temp/ggez/examples/astroblasto.rs:321
  20: astroblasto::MainState::new
             at /home/user/temp/ggez/examples/astroblasto.rs:401
  21: astroblasto::main
             at /home/user/temp/ggez/examples/astroblasto.rs:675
  22: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:98
  23: std::rt::lang_start
             at /checkout/src/libstd/panicking.rs:433
             at /checkout/src/libstd/panic.rs:361
             at /checkout/src/libstd/rt.rs:57
  24: main
  25: __libc_start_main
  26: _start
```

What a beauty. I'm running Arch Linux and can confirm sound is working.

Thanks!

**Comment by icefoxen** [comment]
That's a good'un!

I am not an expert but it *appears* that the underlying sound library (cpal) is requesting your sound card output a format that the card does not support.  I don't know how to diagnose this but I guess I'll start learning!  If possible, can you please provide:

 * The output of `uname -a`
 * The output of `lspci`
 * If you're bold, the output of [this guy's random script](http://lacocina.nl/detect-alsa-output-capabilities) which appears to list all the encoding formats but I can't figure out how it gets them

**Comment by freiguy1** [comment]
`uname -a`

```
Linux 2pro4u 4.9.22-1-lts #1 SMP Wed Apr 12 19:02:06 CEST 2017 x86_64 GNU/Linux
```

`lspci`

```
00:00.0 Host bridge: Intel Corporation Haswell-ULT DRAM Controller (rev 0b)
00:02.0 VGA compatible controller: Intel Corporation Haswell-ULT Integrated Graphics Controller (rev 0b)
00:03.0 Audio device: Intel Corporation Haswell-ULT HD Audio Controller (rev 0b)
00:04.0 Signal processing controller: Intel Corporation Device 0a03 (rev 0b)
00:14.0 USB controller: Intel Corporation 8 Series USB xHCI HC (rev 04)
00:16.0 Communication controller: Intel Corporation 8 Series HECI #0 (rev 04)
00:1b.0 Audio device: Intel Corporation 8 Series HD Audio Controller (rev 04)
00:1c.0 PCI bridge: Intel Corporation 8 Series PCI Express Root Port 1 (rev e4)
00:1d.0 USB controller: Intel Corporation 8 Series USB EHCI #1 (rev 04)
00:1f.0 ISA bridge: Intel Corporation 8 Series LPC Controller (rev 04)
00:1f.2 SATA controller: Intel Corporation 8 Series SATA Controller 1 [AHCI mode] (rev 04)
00:1f.3 SMBus: Intel Corporation 8 Series SMBus Controller (rev 04)
00:1f.6 Signal processing controller: Intel Corporation 8 Series Thermal (rev 04)
01:00.0 Network controller: Intel Corporation Wireless 7260 (rev 6b)
```

random guy script:

```
Redirecting output to ‘wget-log’.
 0) Digital alsa audio output interface `hw:0,3'
 - device name       = HDA Intel HDMI                                              
 - interface name    = HDMI 0                                                      
 - usb audio class   = (n/a)                                                       
 - character device  = /dev/snd/pcmC0D3p                                           
 - encoding formats  = S16_LE, S32_LE, IEC958_SUBFRAME_LE                          
 - monitor file      = /proc/asound/card0/pcm3p/sub0/hw_params                     
 - stream file       = (n/a)                                                       

 1) Digital alsa audio output interface `hw:0,7'
 - device name       = HDA Intel HDMI                                              
 - interface name    = HDMI 1                                                      
 - usb audio class   = (n/a)                                                       
 - character device  = /dev/snd/pcmC0D7p                                           
 - encoding formats  = S16_LE, S32_LE, IEC958_SUBFRAME_LE                          
 - monitor file      = /proc/asound/card0/pcm7p/sub0/hw_params                     
 - stream file       = (n/a)                                                       

 2) Digital alsa audio output interface `hw:0,8'
 - device name       = HDA Intel HDMI                                              
 - interface name    = HDMI 2                                                      
 - usb audio class   = (n/a)                                                       
 - character device  = /dev/snd/pcmC0D8p                                           
 - encoding formats  = S16_LE, S32_LE, IEC958_SUBFRAME_LE                          
 - monitor file      = /proc/asound/card0/pcm8p/sub0/hw_params                     
 - stream file       = (n/a)                                                       

 3) Analog alsa audio output interface `hw:1,0'
 - device name       = HDA Intel PCH                                               
 - interface name    = ALC3239 Analog                                              
 - usb audio class   = (n/a)                                                       
 - character device  = /dev/snd/pcmC1D0p                                           
 - encoding formats  = S16_LE, S32_LE                                              
 - monitor file      = /proc/asound/card1/pcm0p/sub0/hw_params                     
 - stream file       = (n/a)                                                       
```

**Comment by freiguy1** [comment]
Hmm I fixed it by removing `~/.asoundrc` which contained:

```
pcm.!default {
    type hw
    card 0
    device 3
}
```

which was a thing I added which made my hdmi card default when it was plugged in, however I'm not sure if that actually works.  Anyway, closing! :)
