### ISSUE TITLE
Unable to initialize contexts for unit testing.

### ISSUE THREAD

**Issue by dogunbound** [ggez/ggez#1035]
**Describe the bug**
```---- assets::test::test_load_sprite_batches stdout ----
thread 'assets::test::test_load_sprite_batches' panicked at 'Initializing the event loop outside of the main thread is a significant cross-platform compatibility hazard. If you really, absolutely need to create an EventLoop on a different thread, please use the `EventLoopExtUnix::new_any_thread` function.', /home/dogunbound/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.25.0/src/platform_impl/linux/mod.rs:751:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panicking.rs:116:14
   2: winit::platform_impl::platform::assert_is_main_thread
             at /home/dogunbound/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.25.0/src/platform_impl/linux/mod.rs:751:9
   3: winit::platform_impl::platform::EventLoop<T>::new
             at /home/dogunbound/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.25.0/src/platform_impl/linux/mod.rs:565:9
   4: winit::event_loop::EventLoop<T>::with_user_event
             at /home/dogunbound/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.25.0/src/event_loop.rs:134:25
   5: winit::event_loop::EventLoop<()>::new
             at /home/dogunbound/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.25.0/src/event_loop.rs:120:9
   6: ggez::context::Context::from_conf
             at /home/dogunbound/.cargo/registry/src/github.com-1ecc6299db9ec823/ggez-0.7.0/src/context.rs:87:27
   7: ggez::context::ContextBuilder::build
             at /home/dogunbound/.cargo/registry/src/github.com-1ecc6299db9ec823/ggez-0.7.0/src/context.rs:265:9
   8: quest_hearth::assets::test::test_load_sprite_batches
             at ./src/assets.rs:271:23
   9: quest_hearth::assets::test::test_load_sprite_batches::{{closure}}
             at ./src/assets.rs:270:5
  10: core::ops::function::FnOnce::call_once
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/ops/function.rs:227:5
  11: core::ops::function::FnOnce::call_once
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.


failures:
    assets::test::test_load_sprite_batches

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.43s

error: test failed, to rerun pass '--bin quest_hearth'
```

**To Reproduce**
Build a context inside of a unit test case.

**Expected behavior**
Allow me to build as many contexts inside of unit test cases. I don't care if multiple windows keep popping up during testing. I need to be able to test my code.

**Screenshots or pasted code**
```#[cfg(test)]
mod test {
    use super::*;
    use ggez::ContextBuilder;

    #[test]
    fn test_load_sprite_batches() {
        let mut ctx = ContextBuilder::new("test", "slohobo")
            .build()
            .expect("Failed to initialize ggez context!")
            .0;

        match load_sprite_batches(&mut ctx) {
            Ok(v) => {
                assert!(v.keys().len() >= 1);
            }
            Err(e) => {
                eprintln!("{}", e);
                assert!(false);
            }
        };
    }
}
```

**Hardware and Software:**
 - ggez version: 0.7.0
 - OS: Arch Linux
 - Graphics card: GTX 1060 6GB
 - Graphics card drivers: nvidia proprietary

**Comment by dogunbound** [comment]
cargo test -- --test-threads=1

**Comment by PSteinhaus** [comment]
Yeah, it's a bit annoying. Glad you found the workaround.
