### ISSUE TITLE
`graphics_settings` example crashes when swithing to fullscreen

### ISSUE THREAD

**Issue by 64kramsystem** [ggez/ggez#1065]
**Describe the bug**

When switching to fullscreen the example `graphics_settings`, the program crashes

**To Reproduce**

`cargo run --example graphics_settings` -> tap `f`

**Expected behavior**

No crash.

**Screenshots or pasted code**

```
$ git co 0.8.0-rc0
HEAD is now at f6c34de Merge pull request #1040 from ggez/devel
$ cargo run --example graphics_settings
    Finished dev [optimized + debuginfo] target(s) in 0.10s
     Running `target/debug/examples/graphics_settings`
GRAPHICS SETTING EXAMPLE:
    F: toggle fullscreen
    Up/Down: Zoom in/out
    Spacebar: Toggle whether or not to resize the projection when the window is resized

    To see command-line options, run with `cargo run --example graphics_settings -- --help`

Resized screen to 800, 600
thread 'main' panicked at 'wgpu error: Validation Error

Caused by:
    In a RenderPass
      note: encoder = `<CommandBuffer-(0, 75, Vulkan)>`
    In a set_scissor_rect command
    Invalid ScissorRect parameters

', /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.12.0/src/backend/direct.rs:2273:5
stack backtrace:
   0: rust_begin_unwind
             at /rustc/38b72154ded23847cd08a796d0c6708b5efac265/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/38b72154ded23847cd08a796d0c6708b5efac265/library/core/src/panicking.rs:142:14
   2: wgpu::backend::direct::default_error_handler
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.12.0/src/backend/direct.rs:2273:5
   3: core::ops::function::Fn::call
             at /rustc/38b72154ded23847cd08a796d0c6708b5efac265/library/core/src/ops/function.rs:77:5
   4: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/38b72154ded23847cd08a796d0c6708b5efac265/library/alloc/src/boxed.rs:1948:9
   5: wgpu::backend::direct::ErrorSinkRaw::handle_error
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.12.0/src/backend/direct.rs:2259:17
   6: wgpu::backend::direct::Context::handle_error
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.12.0/src/backend/direct.rs:194:9
   7: <wgpu::backend::direct::Context as wgpu::Context>::command_encoder_end_render_pass
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.12.0/src/backend/direct.rs:2010:13
   8: core::ptr::drop_in_place<wgpu::RenderPass>
             at /rustc/38b72154ded23847cd08a796d0c6708b5efac265/library/core/src/ptr/mod.rs:487:1
   9: core::ptr::drop_in_place<ggez::graphics::internal_canvas::InternalCanvas>
             at /rustc/38b72154ded23847cd08a796d0c6708b5efac265/library/core/src/ptr/mod.rs:487:1
  10: ggez::graphics::internal_canvas::InternalCanvas::finish
             at ./src/graphics/internal_canvas.rs:500:5
  11: ggez::graphics::canvas::Canvas::finalize
             at ./src/graphics/canvas.rs:475:9
  12: ggez::graphics::canvas::Canvas::finish
             at ./src/graphics/canvas.rs:377:9
  13: <graphics_settings::MainState as ggez::event::EventHandler>::draw
             at ./examples/graphics_settings.rs:134:9
  14: ggez::event::run::{{closure}}
             at ./src/event.rs:538:33
  15: winit::platform_impl::platform::sticky_exit_callback
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.26.1/src/platform_impl/linux/mod.rs:753:5
  16: winit::platform_impl::platform::x11::EventLoop<T>::run_return
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.26.1/src/platform_impl/linux/x11/mod.rs:293:17
  17: winit::platform_impl::platform::x11::EventLoop<T>::run
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.26.1/src/platform_impl/linux/x11/mod.rs:392:9
  18: winit::platform_impl::platform::EventLoop<T>::run
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.26.1/src/platform_impl/linux/mod.rs:669:56
  19: winit::event_loop::EventLoop<T>::run
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.26.1/src/event_loop.rs:154:9
  20: ggez::event::run
             at ./src/event.rs:299:5
  21: graphics_settings::main
             at ./examples/graphics_settings.rs:248:5
  22: core::ops::function::FnOnce::call_once
             at /rustc/38b72154ded23847cd08a796d0c6708b5efac265/library/core/src/ops/function.rs:248:5
```

**Hardware and Software:**
 - ggez version: 0.8.0-rc0
 - OS: Linux (Ubuntu 20.04)
 - Graphics card: Should be (not 100% sure, though) UHD Graphics 620 (Whiskey Lake)
 - Graphics card drivers: Open source

**Comment by PSteinhaus** [comment]
Could you try this again on devel, please?

I managed to reproduce the crash on 0.8.0-rc0, but not on devel. As this seems to be a scissor rect related problem chances are that this has recently been fixed.

**Comment by 64kramsystem** [comment]
Thanks for the attention :smile: 

I confirm that it works on devel; closing.
