### ISSUE TITLE
thread 'main' panicked at 'assertion failed: capacity > 0'

### ISSUE THREAD

**Issue by buxx** [ggez/ggez#1168]
**Describe the bug**

On my project, Rust panic on following assert when use devel branch since [81544de231c1f9dcce530a2b0aa09d4b1f423ed7](https://github.com/ggez/ggez/commit/81544de231c1f9dcce530a2b0aa09d4b1f423ed7) (I don't understand why this commit in particular) : 

```rust
    fn new_wgpu(
        wgpu: &WgpuContext,
        bind_layout: ArcBindGroupLayout,
        image: Image,
        capacity: usize,
        ordered: bool,
    ) -> Self {
        assert!(capacity > 0);
```

```
thread 'main' panicked at 'assertion failed: capacity > 0', /home/bastiensevajol/.cargo/git/checkouts/ggez-ed9d3cec31fdee53/81544de/src/graphics/instance.rs:77:9
```

**To Reproduce**

* `git clone https://github.com/buxx/OpenCombat`
* `cd OpenCombat`
* `git checkout experimental-ggez`
* `cargo run Server --server-bind-address 'tcp://0.0.0.0:4255' --server-rep-address 'tcp://0.0.0.0:4256'`

**Expected behavior**

Don't crash

**Screenshots or pasted code**

See *To Reproduce*

**Hardware and Software:**
 - ggez version: devel
 - OS: Ubuntu 22.04
 - Graphics card: For example, NVidia GTX 660, Intel Iris 520, etc.
 - Graphics card drivers: VGA compatible controller: Intel Corporation Device 9a49 (rev 01)

**Comment by buxx** [comment]
Any idea about what I can make in my game code which produce this assertion error ? ggez examples looks not crashed. So I imagine is it specific to my code.

**Comment by nobbele** [comment]
Can you send a stack backtrace?

**Comment by buxx** [comment]
@nobbele There is : 

```
thread 'main' panicked at 'assertion failed: capacity > 0', /home/bastiensevajol/.cargo/git/checkouts/ggez-ed9d3cec31fdee53/81544de/src/graphics/instance.rs:77:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/panicking.rs:64:14
   2: core::panicking::panic
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/panicking.rs:111:5
   3: ggez::graphics::instance::InstanceArray::new_wgpu
             at /home/bastiensevajol/.cargo/git/checkouts/ggez-ed9d3cec31fdee53/81544de/src/graphics/instance.rs:77:9
   4: ggez::graphics::instance::InstanceArray::flush_wgpu
             at /home/bastiensevajol/.cargo/git/checkouts/ggez-ed9d3cec31fdee53/81544de/src/graphics/instance.rs:204:27
   5: <ggez::graphics::instance::InstanceArray as ggez::graphics::draw::Drawable>::draw
             at /home/bastiensevajol/.cargo/git/checkouts/ggez-ed9d3cec31fdee53/81544de/src/graphics/instance.rs:311:9
   6: ggez::graphics::canvas::Canvas::draw
             at /home/bastiensevajol/.cargo/git/checkouts/ggez-ed9d3cec31fdee53/81544de/src/graphics/canvas.rs:369:9
   7: opencombat::graphics::Graphics::draw_map
             at ./src/graphics/mod.rs:316:9
   8: <opencombat::engine::Engine as ggez::event::EventHandler>::draw
             at ./src/engine/mod.rs:144:9
   9: ggez::event::run::{{closure}}
             at /home/bastiensevajol/.cargo/git/checkouts/ggez-ed9d3cec31fdee53/81544de/src/event.rs:530:33
  10: winit::platform_impl::platform::sticky_exit_callback
             at /home/bastiensevajol/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.27.5/src/platform_impl/linux/mod.rs:849:9
  11: winit::platform_impl::platform::x11::EventLoop<T>::run_return::single_iteration
             at /home/bastiensevajol/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.27.5/src/platform_impl/linux/x11/mod.rs:363:17
  12: winit::platform_impl::platform::x11::EventLoop<T>::run_return
             at /home/bastiensevajol/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.27.5/src/platform_impl/linux/x11/mod.rs:448:31
  13: winit::platform_impl::platform::x11::EventLoop<T>::run
             at /home/bastiensevajol/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.27.5/src/platform_impl/linux/x11/mod.rs:503:25
  14: winit::platform_impl::platform::EventLoop<T>::run
             at /home/bastiensevajol/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.27.5/src/platform_impl/linux/mod.rs:755:56
  15: winit::event_loop::EventLoop<T>::run
             at /home/bastiensevajol/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.27.5/src/event_loop.rs:278:9
  16: ggez::event::run
             at /home/bastiensevajol/.cargo/git/checkouts/ggez-ed9d3cec31fdee53/81544de/src/event.rs:291:5
  17: opencombat::main
             at ./src/main.rs:84:5
  18: core::ops::function::FnOnce::call_once
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/ops/function.rs:507:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread '<unnamed>' panicked at 'Channel was closed when try to receive messages to send: RecvError', src/network/mod.rs:239:56
stack backtrace:
   0: rust_begin_unwind
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/panicking.rs:64:14
   2: core::result::unwrap_failed
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/result.rs:1791:5
   3: core::result::Result<T,E>::expect
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/result.rs:1070:23
   4: opencombat::network::Network::start_pub::{{closure}}
             at ./src/network/mod.rs:239:28
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by buxx** [comment]
There is a second with last devel commit : 

```
thread 'main' panicked at 'assertion failed: capacity > 0', /home/bastiensevajol/.cargo/git/checkouts/ggez-ed9d3cec31fdee53/7d4de68/src/graphics/instance.rs:77:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/panicking.rs:64:14
   2: core::panicking::panic
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/panicking.rs:111:5
   3: ggez::graphics::instance::InstanceArray::new_wgpu
             at /home/bastiensevajol/.cargo/git/checkouts/ggez-ed9d3cec31fdee53/7d4de68/src/graphics/instance.rs:77:9
   4: ggez::graphics::instance::InstanceArray::flush_wgpu
             at /home/bastiensevajol/.cargo/git/checkouts/ggez-ed9d3cec31fdee53/7d4de68/src/graphics/instance.rs:204:27
   5: <ggez::graphics::instance::InstanceArray as ggez::graphics::draw::Drawable>::draw
             at /home/bastiensevajol/.cargo/git/checkouts/ggez-ed9d3cec31fdee53/7d4de68/src/graphics/instance.rs:309:9
   6: ggez::graphics::canvas::Canvas::draw
             at /home/bastiensevajol/.cargo/git/checkouts/ggez-ed9d3cec31fdee53/7d4de68/src/graphics/canvas.rs:363:9
   7: opencombat::graphics::Graphics::draw_map
             at ./src/graphics/mod.rs:316:9
   8: <opencombat::engine::Engine as ggez::event::EventHandler>::draw
             at ./src/engine/mod.rs:144:9
   9: ggez::event::run::{{closure}}
             at /home/bastiensevajol/.cargo/git/checkouts/ggez-ed9d3cec31fdee53/7d4de68/src/event.rs:525:33
  10: winit::platform_impl::platform::sticky_exit_callback
             at /home/bastiensevajol/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.27.5/src/platform_impl/linux/mod.rs:849:9
  11: winit::platform_impl::platform::x11::EventLoop<T>::run_return::single_iteration
             at /home/bastiensevajol/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.27.5/src/platform_impl/linux/x11/mod.rs:363:17
  12: winit::platform_impl::platform::x11::EventLoop<T>::run_return
             at /home/bastiensevajol/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.27.5/src/platform_impl/linux/x11/mod.rs:448:31
  13: winit::platform_impl::platform::x11::EventLoop<T>::run
             at /home/bastiensevajol/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.27.5/src/platform_impl/linux/x11/mod.rs:503:25
  14: winit::platform_impl::platform::EventLoop<T>::run
             at /home/bastiensevajol/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.27.5/src/platform_impl/linux/mod.rs:755:56
  15: winit::event_loop::EventLoop<T>::run
             at /home/bastiensevajol/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.27.5/src/event_loop.rs:278:9
  16: ggez::event::run
             at /home/bastiensevajol/.cargo/git/checkouts/ggez-ed9d3cec31fdee53/7d4de68/src/event.rs:286:5
  17: opencombat::main
             at ./src/main.rs:84:5
  18: core::ops::function::FnOnce::call_once
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/ops/function.rs:507:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread '<unnamed>' panicked at 'Channel was closed when try to receive messages to send: RecvError', src/network/mod.rs:239:56
stack backtrace:
   0: rust_begin_unwind
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/panicking.rs:64:14
   2: core::result::unwrap_failed
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/result.rs:1791:5
   3: core::result::Result<T,E>::expect
             at /rustc/fc594f15669680fa70d255faec3ca3fb507c3405/library/core/src/result.rs:1070:23
   4: opencombat::network::Network::start_pub::{{closure}}
             at ./src/network/mod.rs:239:28
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by buxx** [comment]
```
             at ./src/graphics/mod.rs:316:9
```

is

```rust
canvas.draw(&self.map_interiors_batch, draw_param);
```

and `./src/engine/mod.rs:144:9` is non-relevant code.

**Comment by buxx** [comment]
Got it ! 

```diff
diff --git a/src/graphics/mod.rs b/src/graphics/mod.rs
index dd1e1bf..f007b98 100644
--- a/src/graphics/mod.rs
+++ b/src/graphics/mod.rs
@@ -313,7 +313,9 @@ impl Graphics {
         canvas.draw(&self.map_background_batch, draw_param);
 
         // Map interior sprites
-        canvas.draw(&self.map_interiors_batch, draw_param);
+        if self.map_interiors_batch.instances().len() > 0 {
+            canvas.draw(&self.map_interiors_batch, draw_param);
+        }
 
         Ok(())
     }
```

Crash is when instance array is empty. It is an old bug (https://github.com/ggez/ggez/issues/927) maybe reintroduced with 0.8 rewrite ?

**Comment by jazzfool** [comment]
https://github.com/ggez/ggez/blob/devel/src/graphics/instance.rs#L208 this should be guarded for only non-empty instances
it would probably be best done here https://github.com/ggez/ggez/blob/devel/src/graphics/instance.rs#L309 where we skip pushing the draw altogether is instances is empty

**Comment by Vixeliz** [comment]
Closing this as it appears to be fixed.
