### ISSUE TITLE
Not usable on Linux with modern Intel graphics

### ISSUE THREAD

**Issue by jplatte** [ggez/ggez#212]
This seems to be an issue with Intel graphics + Linux + SDL2 + srgba that I've discovered in a personal project. It affects ggez too, so I thought you might want to know. Running any of the examples on either of my two machines (one with Intel HD5500 graphics, one with Intel Iris Pro 6200 graphics) results in the following error:

```
% RUST_BACKTRACE=1 cargo run --example hello_world
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `target/debug/examples/hello_world`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: WindowError(SdlError("Could not create GL context"))', /checkout/src/libcore/result.rs:906:4
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:68
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:57
             at /checkout/src/libstd/panicking.rs:381
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:397
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:577
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:538
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:522
   7: rust_begin_unwind
             at /checkout/src/libstd/panicking.rs:498
   8: core::panicking::panic_fmt
             at /checkout/src/libcore/panicking.rs:71
   9: core::result::unwrap_failed
             at /checkout/src/libcore/macros.rs:23
  10: <core::result::Result<T, E>>::unwrap
             at /checkout/src/libcore/result.rs:772
  11: hello_world::main
             at examples/hello_world.rs:64
  12: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:99
  13: std::rt::lang_start
             at /checkout/src/libstd/panicking.rs:459
             at /checkout/src/libstd/panic.rs:365
             at /checkout/src/libstd/rt.rs:58
  14: main
  15: __libc_start_main
  16: _start
```

**Comment by termhn** [comment]
Looks the same as #194 -- this is a bug with newish Mesa drivers that is now fixed in the git master branch. If you want a fix now, go grab that version. If you don't mind waiting, you could wait till it rolls out to whatever distro you're using.

**Comment by jplatte** [comment]
Ah thanks, didn't think about searching closed issues! It does indeed work after I built & installed the latest mesa and restarted my desktop. 😄
