### ISSUE TITLE
confusing ResourceNotFound error

### ISSUE THREAD

**Issue by AaronM04** [ggez/ggez#26]
Hi, I tried to get started with ggez by putting the hello_world example into a new project, and I get this error:

```
$ RUST_BACKTRACE=1 cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `target/debug/ggez_test`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ResourceNotFound("DejaVuSerif.ttf")', /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/result.rs:870
stack backtrace:
   1:     0x55984fe3d5cc - std::sys::imp::backtrace::tracing::imp::write::h9c41d2f69e5caabf
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:42
   2:     0x55984fe3fd3e - std::panicking::default_hook::{{closure}}::hcc803c8663cda123
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:351
   3:     0x55984fe3f944 - std::panicking::default_hook::hd5bda4e453dfb4be
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:367
   4:     0x55984fe4011b - std::panicking::rust_panic_with_hook::hffbc74969c7b5d87
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:555
   5:     0x55984fe3ffb4 - std::panicking::begin_panic::hc4c5d184a1e3fb7c
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:517
   6:     0x55984fe3fed9 - std::panicking::begin_panic_fmt::h34f5b320b0f94559
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:501
   7:     0x55984fe3fe67 - rust_begin_unwind
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:477
   8:     0x55984fe67a8d - core::panicking::panic_fmt::h1016b85b51d1931f
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/panicking.rs:69
   9:     0x55984fd2b935 - core::result::unwrap_failed::h32d58e2d95a73da2
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/macros.rs:29
  10:     0x55984fd26ee6 - <core::result::Result<T, E>>::unwrap::h3d9e6ceea8190f28
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/result.rs:745
  11:     0x55984fd36509 - <ggez_test::MainState as ggez::game::GameState>::load::h61298cceab611496
                        at /home/aaron/dev/rust/conway/ggez_test/src/main.rs:23
  12:     0x55984fd281c8 - <ggez::game::Game<'a, S>>::new::ha71647cbf4697e3a
                        at /home/aaron/.cargo/registry/src/github.com-1ecc6299db9ec823/ggez-0.2.1/src/game.rs:123
  13:     0x55984fd36a3d - ggez_test::main::h0bd4c5cea99ba3c8
                        at /home/aaron/dev/rust/conway/ggez_test/src/main.rs:53
  14:     0x55984fe46faa - __rust_maybe_catch_panic
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libpanic_unwind/lib.rs:98
  15:     0x55984fe40886 - std::rt::lang_start::ha0568cc91d8c5b09
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:436
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panic.rs:361
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/rt.rs:57
  16:     0x55984fd36d72 - main
  17:     0x7f2ad825d400 - __libc_start_main
  18:     0x55984fd1eb49 - _start
  19:                0x0 - <unknown>
```

I don't understand why I am getting this error, because I have the required resource in the right location:
```
$ ls target/debug/resources/
DejaVuSerif.ttf
```

I am running the latest rust nightly, if that makes a difference:

```
$ rustc --version
rustc 1.16.0-nightly (ff591b6dc 2017-01-15)
```

**Comment by AaronM04** [comment]
Using strace I discovered that it's checking in two directories for the resource: `<repo_root>/target/resources/DejaVuSerif.ttf` and `~/.local/share/ggez/helloworld`. This lets me continue work but I think other people will run into this issue when they start using ggez. I recommend making the error contain a list of paths that were checked. I can make a pull request if you can just point me at where in ggez this error comes from...

**Comment by icefoxen** [comment]
Grr, I wish this were less irritating...  It does the Right Thing, but that's generally not the thing you actually want when starting a project.  Especially since it appears that cargo is a little permissive on what directory it actually runs things from.  Maybe we should come up with a way to make a `build.rs` that points to the right place all the time, or allow an environment variable to set the path, but both of those somewhat increase the barrier to entry.

For now, putting the paths in the error message is a good idea.  Pull requests would be welcome; the relevant code is in `Filesystem::open()` at https://github.com/ggez/ggez/blob/master/src/filesystem.rs#L163 .  I would suggest putting a Vec of Path's in the `ResourceNotFound` error type showing where ggez is searching, and then perhaps making the `Display` trait for `GameError` a bit more informative.

Thank you for the report!

**Comment by AaronM04** [comment]
I made a PR but forgot the second part of your suggestion "and then perhaps making the Display trait for GameError a bit more informative". I'll implement that if/when I have more time.

**Comment by icefoxen** [comment]
Thanks!  This honestly makes life a lot nicer.  I've added some extra information to `GameError::ResourceNotFound` as well.
