### ISSUE TITLE
Build Error: Failed to run alsa-sys

### ISSUE THREAD

**Issue by johvahn2** [ggez/ggez#278]
I am unable to get this thing built 

full error message:
```

error: failed to run custom build command for `alsa-sys v0.1.1`
process didn't exit successfully: `/home/johvahn/Documents/Projects/RUST/GAMES/ggez_basic/target/debug/build/alsa-sys-1ffa52db67c41f96/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "Failed to run `\"pkg-config\" \"--libs\" \"--cflags\" \"alsa\"`: No such file or directory (os error 2)"', /checkout/src/libcore/result.rs:906:4
note: Run with `RUST_BACKTRACE=1` for a backtrace.

warning: build failed, waiting for other jobs to finish...
error: build failed
```

i tried doing this solution that was posted: 
`sudo apt install libasound2-dev
`
but im still getting the same error

**Comment by icefoxen** [comment]
Hi, sorry to hear that.  What Linux distro are you on?  I can whip up a VM and try to replicate this.

What do you get when you just try to run the command `pkg-config --libs --cflags alsa` in a command line?

**Comment by johvahn2** [comment]
i am using Ubuntu 17.10

and running `pkg-config --libs --cflags alsa` i get 
```
The program 'pkg-config' can be found in the following packages:
 * pkg-config
 * pkgconf
Try: sudo apt install <selected package>
```

**Comment by icefoxen** [comment]
Aha.  `pkg-config` isn't installed, which is a program used to keep track of where C libraries (like libasound2) are kept.  Try `sudo apt install pkg-config` and see if it works then.  You might also need to install the `build-essentials` package.

See if that works, and I'll update the install docs.

**Comment by johvahn2** [comment]
now im getting
```
error[E0243]: wrong number of type arguments: expected 1, found 0
  --> src/main.rs:10:35
   |
10 |     fn new(_ctx: &mut Context) -> GameResult {
   |                                   ^^^^^^^^^^ expected 1 type argument

error: aborting due to previous error

error: Could not compile `ggez_basic`.
```

**Comment by icefoxen** [comment]
`GameResult` is a generic type so you need to tell it what kind of `GameResult` it is, see https://github.com/ggez/ggez/blob/master/examples/hello_world.rs#L23

**Comment by johvahn2** [comment]
Alright both problem have been fixed but now im getting

```
error: linking with `cc` failed: exit code: 1
  |
  = note: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-m64" "-L" "/home/johvahn/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "/home/johvahn/Documents/Projects/RUST/GAMES/ggez_basic/target/debug/deps/ggez_basic-96e17f413d700561.ggez_basic0.rcgu.o" "/home/johvahn/Documents/Projects/RUST/GAMES/ggez_basic/target/debug/deps/ggez_basic-96e17f413d700561.ggez_basic1.rcgu.o" "/home/johvahn/Documents/Projects/RUST/GAMES/ggez_basic/target/debug/deps/ggez_basic-96e17f413d700561.ggez_basic10.rcgu.o" "/home/johvahn/Documents/Projects/RUST/GAMES/ggez_basic/target/debug/deps/ggez_basic-96e17f413d700561.ggez_basic11.rcgu.o" "/home/johvahn/Documents/Projects/RUST/GAMES/ggez_basic/target/debug/deps/ggez_basic-96e17f413d700561.ggez_basic12.rcgu.o" "/home/johvahn/Documents/Projects/RUST/GAMES/ggez_basic/target/debug/deps/ggez_basic-96e17f413d700561.ggez_basic13.rcgu.o" "/home/johvahn/Documents/Projects/RUST/GAMES/ggez_basic/target/debug/deps/ggez_basic-96e17f413d700561.ggez_basic14.rcgu.o" "/home/johvahn/Documents/Projects/RUST/GAMES/ggez_basic/target/debug/deps/ggez_basic-96e17f413d700561.ggez_basic15.rcgu.o" "/home/johvahn/Documents/Projects/RUST/GAMES/ggez_basic/target/debug/deps/ggez_basic-96e17f413d700561.ggez_basic2.rcgu.o" "/home/johvahn/Documents/Projects/RUST/GAMES/ggez_basic/target/debug/deps/ggez_basic-96e17f413d700561.ggez_basic3.rcgu.o" "/home/johvahn/Documents/Projects/RUST/GAMES/ggez_basic/target/debug/deps/ggez_basic-96e17f413d700561.ggez_basic4.rcgu.o" "/home/johvahn/Documents/Projects/RUST/GAMES/ggez_basic/target/debug/deps/ggez_basic-96e17f413d700561.ggez_basic5.rcgu.o" "/home/johvahn/Documents/Projects/RUST/GAMES/ggez_basic/target/debug/deps/ggez_basic-96e17f413d700561.ggez_basic6.rcgu.o" "/home/johvahn/Documents/Projects/RUST/GAMES/ggez_basic/target/debug/deps/ggez_basic-96e17f413d700561.ggez_basic7.rcgu.o" "/home/johvahn/Documents/Projects/RUST/GAMES/ggez_basic/target/debug/deps/ggez_basic-96e17f413d700561.ggez_basic8.rcgu.o" "/home/johvahn/Documents/Projects/RUST/GAMES/ggez_basic/target/debug/deps/ggez_basic-96e17f413d700561.ggez_basic9.rcgu.o" "-o" "/home/johvahn/Documents/Projects/RUST/GAMES/ggez_basic/target/debug/deps/ggez_basic-96e17f413d700561" "/home/johvahn/Documents/Projects/RUST/GAMES/ggez_basic/target/debug/deps/ggez_basic-96e17f413d700561.crate.allocator.rcgu.o" "-Wl,--gc-sections" "-pie" "-Wl,-z,relro,-z,now" "-nodefaultlibs""-L" "/home/johvahn/Documents/Projects/RUST/GAMES/ggez_basic/target/debug/deps" "-L" "/usr/lib/x86_64-linux-gnu" "-L" "/home/johvahn/Documents/Projects/RUST/GAMES/ggez_basic/target/debug/build/bzip2-sys-d1b80e20a34f3efc/out" "-L" "/home/johvahn/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "/home/johvahn/Documents/Projects/RUST/GAMES/ggez_basic/target/debug/deps/libggez-3affe5e8b55aad17.rlib" "/home/johvahn/Documents/Projects/RUST/GAMES/ggez_basic/target/debug/deps/libapp_dirs-50f61d103599d50d.rlib" "/home/johvahn/Documents/Projects/RUST/GAMES/ggez_basic/target/debug/deps/libzip-17aed6ad21cc6f4f.rlib" "/home/johvahn/Documents/Projects/RUST/GAMES/ggez_basic/target/debug/deps/libmsdos_time-60bee65583936409.rlib" "/home/johvahn/Documents/Projects/RUST/GAMES/ggez_basic/target/debug/deps/libbzip2-5d1abdd52609b6e7.rlib" "/home/johvahn/Documents/Projects/RUST/GAMES/ggez_basic/target/debug/deps/liblyon-0ce51d71c7eaade6.rlib" "/home/johvahn/Documents/Projects/RUST/GAMES/ggez_basic/target/debug/deps/libgfx-3bc8b39dd93a5d59.rlib" "/home/johvahn/Documents/Projects/RUST/GAMES/ggez_basic/target/debug/deps/libgfx_window_sdl-056aa53dd8cbd3b9.rlib" "/home/johvahn/Documents/Projects/RUST/GAMES/ggez_basic/target/debug/deps/libsdl2-c5dee5a5d3b0b0bb.rlib" "/home/johvahn/Documents/Projects/RUST/GAMES/ggez_basic/target/debug/deps/libsdl2_sys-e622dc32d5e03269.rlib" "/home/johvahn/Documents/Projects/RUST/GAMES/ggez_basic/target/debug/deps/libbitflags-580439101d503740.rlib" "/home/johvahn/Documents/Projects/RUST/GAMES/ggez_basic/target/debug/deps/libnum-0124fb718172eda3.rlib" "/home/johvahn/Documents/Projects/RUST/GAMES/ggez_basic/target/debug/deps/libtoml-f7d9a14a3746222a.rlib" "/home/johvahn/Documents/Projects/RUST/GAMES/ggez_basic/target/debug/deps/liblyon_extra-a8938e326909733f.rlib" "/home/johvahn/Documents/Projects/RUST/GAMES/ggez_basic/target/debug/deps/liblyon_svg-f0271520d493e154.rlib" "/home/johvahn/Documents/Projects/RUST/GAMES/ggez_basic/target/debug/deps/libsvgparser-4df71230a0b9c368.rlib" "/home/johvahn/Documents/Projects/RUST/GAMES/ggez_basic/target/debug/deps/libphf-790b66cc9d3a57fe.rlib" "/home/johvahn/Documents/Projects/RUST/GAMES/ggez_basic/target/debug/deps/librodio-8db4a4983e54d98e.rlib" "/home/johvahn/Documents/Projects/RUST/GAMES/ggez_basic/target/debug/deps/libcgmath-fed21d2a1bea66d7.rlib" "/home/johvahn/Documents/Projects/RUST/GAMES/ggez_basic/target/debug/deps/liblewton-cacce74fed013c83.rlib" "/home/johvahn/Documents/Projects/RUST/GAMES/ggez_basic/target/debug/deps/libogg-a8b7677baf54492b.rlib" "/home/johvahn/Documents/Projects/RUST/GAMES/ggez_basic/target/debug/deps/libcpal-ae41c4e35d2e5039.rlib" "/home/johvahn/Documents/Projects/RUST/GAMES/ggez_basic/target/debug/deps/libfutures-c7d1126177858a4d.rlib" "/home/johvahn/Documents/Projects/RUST/GAMES/ggez_basic/target/debug/deps/libclaxon-88fb40cb6a17fa61.rlib" "/home/johvahn/Documents/Projects/RUST/GAMES/ggez_basic/target/debug/deps/liblazy_static-eb026ce1200efaef.rlib" "/home/johvahn/Documents/Projects/RUST/GAMES/ggez_basic/target/debug/deps/libimage-bb606bc77fd6e4b8.rlib" "/home/johvahn/Documents/Projects/RUST/GAMES/ggez_basic/target/debug/deps/libscoped_threadpool-e7affe6fa31fd89e.rlib" "/home/johvahn/Documents/Projects/RUST/GAMES/ggez_basic/target/debug/deps/libjpeg_decoder-868a3a59a50b4151.rlib" "/home/johvahn/Documents/Projects/RUST/GAMES/ggez_basic/target/debug/deps/libenum_primitive-36251f2b9732d8e7.rlib" "/home/johvahn/Documents/Projects/RUST/GAMES/ggez_basic/target/debug/deps/libnum_rational-5c6bf3c64b6910e8.rlib" "/home/johvahn/Documents/Projects/RUST/GAMES/ggez_basic/target/debug/deps/libnalgebra-ce7c03eb68a8ae1c.rlib" "/home/johvahn/Documents/Projects/RUST/GAMES/ggez_basic/target/debug/deps/libalga-cf726947d6923110.rlib" "/home/johvahn/Documents/Projects/RUST/GAMES/ggez_basic/target/debug/deps/libnum_complex-ee4e60ee115ae0b3.rlib" "/home/johvahn/Documents/Projects/RUST/GAMES/ggez_basic/target/debug/deps/librustc_serialize-3daf7fbbbeb27b1f.rlib" "/home/johvahn/Documents/Projects/RUST/GAMES/ggez_basic/target/debug/deps/libhound-efe8ce4ed45d541b.rlib" "/home/johvahn/Documents/Projects/RUST/GAMES/ggez_basic/target/debug/deps/librusttype-7f16f153553f3099.rlib" "/home/johvahn/Documents/Projects/RUST/GAMES/ggez_basic/target/debug/deps/liblinked_hash_map-74fbbbe9e0304878.rlib" "/home/johvahn/Documents/Projects/RUST/GAMES/ggez_basic/target/debug/deps/libstb_truetype-bdaa61647c4920ca.rlib" "/home/johvahn/Documents/Projects/RUST/GAMES/ggez_basic/target/debug/deps/libbyteorder-c37288ac01f86578.rlib" "/home/johvahn/Documents/Projects/RUST/GAMES/ggez_basic/target/debug/deps/libarrayvec-534816b8b1a3362e.rlib" "/home/johvahn/Documents/Projects/RUST/GAMES/ggez_basic/target/debug/deps/libgfx_device_gl-21ef8aa2b13568c5.rlib" "/home/johvahn/Documents/Projects/RUST/GAMES/ggez_basic/target/debug/deps/libgfx_gl-67a9c8c8bc7801b4.rlib" "/home/johvahn/Documents/Projects/RUST/GAMES/ggez_basic/target/debug/deps/libflate2-6705244451f88a60.rlib" "/home/johvahn/Documents/Projects/RUST/GAMES/ggez_basic/target/debug/deps/libminiz_oxide_c_api-424d1e384199ef7f.rlib" "/home/johvahn/Documents/Projects/RUST/GAMES/ggez_basic/target/debug/deps/libminiz_oxide-c05aa4a2e6472926.rlib" "/home/johvahn/Documents/Projects/RUST/GAMES/ggez_basic/target/debug/deps/libcrc-8434156fe6b783bf.rlib" "/home/johvahn/Documents/Projects/RUST/GAMES/ggez_basic/target/debug/deps/libpodio-79a2aea5bb24da58.rlib" "/home/johvahn/Documents/Projects/RUST/GAMES/ggez_basic/target/debug/deps/libmatrixmultiply-335fea2340d35c10.rlib" "/home/johvahn/Documents/Projects/RUST/GAMES/ggez_basic/target/debug/deps/librawpointer-460fe0354fa733f7.rlib" "/home/johvahn/Documents/Projects/RUST/GAMES/ggez_basic/target/debug/deps/liblyon_tessellation-98155c3ae1fe53fc.rlib" "/home/johvahn/Documents/Projects/RUST/GAMES/ggez_basic/target/debug/deps/libsid-e5c2998971edd694.rlib" "/home/johvahn/Documents/Projects/RUST/GAMES/ggez_basic/target/debug/deps/libphf_shared-244ddce868888920.rlib" "/home/johvahn/Documents/Projects/RUST/GAMES/ggez_basic/target/debug/deps/libsiphasher-3d17b7424376a55d.rlib" "/home/johvahn/Documents/Projects/RUST/GAMES/ggez_basic/target/debug/deps/libxdg-54ca3b404ac12681.rlib" "/home/johvahn/Documents/Projects/RUST/GAMES/ggez_basic/target/debug/deps/libalsa_sys-89782bea8a499a1b.rlib" "/home/johvahn/Documents/Projects/RUST/GAMES/ggez_basic/target/debug/deps/libapprox-aef52790aa30de99.rlib" "/home/johvahn/Documents/Projects/RUST/GAMES/ggez_basic/target/debug/deps/libgfx_core-0ddadf6efb83967d.rlib" "/home/johvahn/Documents/Projects/RUST/GAMES/ggez_basic/target/debug/deps/libdraw_state-c1c02127d791019a.rlib" "/home/johvahn/Documents/Projects/RUST/GAMES/ggez_basic/target/debug/deps/libbitflags-213974380af4de3a.rlib" "/home/johvahn/Documents/Projects/RUST/GAMES/ggez_basic/target/debug/deps/libordered_float-3d70341205965452.rlib" "/home/johvahn/Documents/Projects/RUST/GAMES/ggez_basic/target/debug/deps/libunreachable-a5f51b4edaf273ba.rlib" "/home/johvahn/Documents/Projects/RUST/GAMES/ggez_basic/target/debug/deps/libvoid-7284d4c3645d0ab9.rlib" "/home/johvahn/Documents/Projects/RUST/GAMES/ggez_basic/target/debug/deps/libbzip2_sys-72e86faaa83d4ae7.rlib" "/home/johvahn/Documents/Projects/RUST/GAMES/ggez_basic/target/debug/deps/libtime-3156ca527fde85b8.rlib" "/home/johvahn/Documents/Projects/RUST/GAMES/ggez_basic/target/debug/deps/libpng-58f56ad314ceb8a9.rlib" "/home/johvahn/Documents/Projects/RUST/GAMES/ggez_basic/target/debug/deps/libdeflate-0fd21ac8ec046ae9.rlib" "/home/johvahn/Documents/Projects/RUST/GAMES/ggez_basic/target/debug/deps/libbyteorder-790206ade36174f5.rlib" "/home/johvahn/Documents/Projects/RUST/GAMES/ggez_basic/target/debug/deps/libinflate-2b8ba172b0ba2ebe.rlib" "/home/johvahn/Documents/Projects/RUST/GAMES/ggez_basic/target/debug/deps/libadler32-f67d02a2e638e418.rlib" "/home/johvahn/Documents/Projects/RUST/GAMES/ggez_basic/target/debug/deps/libnum_iter-d0974736d080bfef.rlib" "/home/johvahn/Documents/Projects/RUST/GAMES/ggez_basic/target/debug/deps/libnum_integer-3b005db9bbec73a3.rlib" "/home/johvahn/Documents/Projects/RUST/GAMES/ggez_basic/target/debug/deps/libbitflags-d9077c45affafc32.rlib" "/home/johvahn/Documents/Projects/RUST/GAMES/ggez_basic/target/debug/deps/libgeneric_array-4478a9469814a983.rlib" "/home/johvahn/Documents/Projects/RUST/GAMES/ggez_basic/target/debug/deps/libtypenum-36eb200548b74eae.rlib" "/home/johvahn/Documents/Projects/RUST/GAMES/ggez_basic/target/debug/deps/librayon-c13ae4ad3a0e9370.rlib" "/home/johvahn/Documents/Projects/RUST/GAMES/ggez_basic/target/debug/deps/librayon_core-d8511ef3c4f9d73e.rlib" "/home/johvahn/Documents/Projects/RUST/GAMES/ggez_basic/target/debug/deps/librand-2cdfae0f5ad3783f.rlib" "/home/johvahn/Documents/Projects/RUST/GAMES/ggez_basic/target/debug/deps/librand-6a87560d96abe585.rlib" "/home/johvahn/Documents/Projects/RUST/GAMES/ggez_basic/target/debug/deps/libnum_cpus-035a7601e57aaafd.rlib" "/home/johvahn/Documents/Projects/RUST/GAMES/ggez_basic/target/debug/deps/liblibc-b1ca85687f9f2272.rlib" "/home/johvahn/Documents/Projects/RUST/GAMES/ggez_basic/target/debug/deps/liblazy_static-e56e0eebe24d7f61.rlib" "/home/johvahn/Documents/Projects/RUST/GAMES/ggez_basic/target/debug/deps/libcoco-2043c141ca7eb4cd.rlib" "/home/johvahn/Documents/Projects/RUST/GAMES/ggez_basic/target/debug/deps/libscopeguard-9e0a1e57e8d75c7d.rlib" "/home/johvahn/Documents/Projects/RUST/GAMES/ggez_basic/target/debug/deps/libeither-fff754c131a22a8a.rlib" "/home/johvahn/Documents/Projects/RUST/GAMES/ggez_basic/target/debug/deps/libgif-d8b31d5f83fbfc17.rlib" "/home/johvahn/Documents/Projects/RUST/GAMES/ggez_basic/target/debug/deps/libcolor_quant-2d7f7d561377fd96.rlib" "/home/johvahn/Documents/Projects/RUST/GAMES/ggez_basic/target/debug/deps/liblzw-6154dd8a14e02cd8.rlib" "/home/johvahn/Documents/Projects/RUST/GAMES/ggez_basic/target/debug/deps/liblyon_path-68dd6ed75815a1ce.rlib" "/home/johvahn/Documents/Projects/RUST/GAMES/ggez_basic/target/debug/deps/liblyon_path_iterator-9ab71bc958a6e613.rlib" "/home/johvahn/Documents/Projects/RUST/GAMES/ggez_basic/target/debug/deps/liblyon_path_builder-d6a95cdb93189da6.rlib" "/home/johvahn/Documents/Projects/RUST/GAMES/ggez_basic/target/debug/deps/liblyon_bezier-a857ffff94c2115a.rlib" "/home/johvahn/Documents/Projects/RUST/GAMES/ggez_basic/target/debug/deps/libarrayvec-81087ad9b50d07ce.rlib" "/home/johvahn/Documents/Projects/RUST/GAMES/ggez_basic/target/debug/deps/libnodrop-6326ec90e8c00d9e.rlib" "/home/johvahn/Documents/Projects/RUST/GAMES/ggez_basic/target/debug/deps/libodds-ac2d1f3d7df28457.rlib" "/home/johvahn/Documents/Projects/RUST/GAMES/ggez_basic/target/debug/deps/liblyon_core-955126bb6b7b5e70.rlib" "/home/johvahn/Documents/Projects/RUST/GAMES/ggez_basic/target/debug/deps/libeuclid-459d903d9d1650b2.rlib" "/home/johvahn/Documents/Projects/RUST/GAMES/ggez_basic/target/debug/deps/libnum_traits-c58e6c21d4389c63.rlib" "/home/johvahn/Documents/Projects/RUST/GAMES/ggez_basic/target/debug/deps/libnum_traits-433e4ce108411370.rlib" "/home/johvahn/Documents/Projects/RUST/GAMES/ggez_basic/target/debug/deps/libserde-fb99f457dc2d077f.rlib" "/home/johvahn/Documents/Projects/RUST/GAMES/ggez_basic/target/debug/deps/liblog-e6324f492dcce3fc.rlib" "/home/johvahn/Documents/Projects/RUST/GAMES/ggez_basic/target/debug/deps/liblog-8ef41fb7fc828f09.rlib" "/home/johvahn/Documents/Projects/RUST/GAMES/ggez_basic/target/debug/deps/libcfg_if-34509d450d3a6e7b.rlib" "/home/johvahn/Documents/Projects/RUST/GAMES/ggez_basic/target/debug/deps/libheapsize-bb8b633c36271c0c.rlib" "/home/johvahn/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-58a9e2944951d97f.rlib" "/home/johvahn/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libpanic_unwind-167b5e977a2ab35c.rlib" "/home/johvahn/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc_jemalloc-17deae1aa65c9467.rlib" "/home/johvahn/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunwind-b8892ba833aa6677.rlib" "/home/johvahn/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc_system-17235785be0fea01.rlib""/home/johvahn/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-2e9b8cf09e3563de.rlib" "/home/johvahn/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-d7195d5e94bc6586.rlib" "/home/johvahn/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd_unicode-963f18f265d9b8d3.rlib" "/home/johvahn/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-48934815da5d2bfb.rlib" "/home/johvahn/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-a6b6fad6cc543169.rlib" "-Wl,-Bdynamic" "-l" "SDL2" "-l" "asound" "-l" "util" "-l" "util" "-l" "dl" "-l" "rt" "-l" "pthread" "-l" "pthread" "-l" "gcc_s" "-l" "c" "-l" "m" "-l" "rt" "-l" "pthread" "-l" "util" "-l" "util"
  = note: /usr/bin/ld: cannot find -lSDL2
          collect2: error: ld returned 1 exit status
```

**Comment by termhn** [comment]
You need to install sdl2... see rust-sdl2 crate for instructions, but it
should be as easy as a

sudo apt-get install libsdl2

Or something similar, don't remember what the apt package name is exactly.

**Comment by johvahn2** [comment]
im getting one leading to the next

im getting this now
`thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: WindowError(SdlError("Could not create GL context"))', /checkout/src/libcore/result.rs:906:4`

**Comment by termhn** [comment]
That is a Mesa bug that means you need to downgrade your Mesa to 17.1 or
upgrade to a bleeding git master build.

**Comment by johvahn2** [comment]
Alright Thank you, all my problems are sloved

**Comment by cata0309** [comment]
If someone is receiving the error on Solus try `sudo eopkg it alsa-lib-devel`

**Comment by th5** [comment]
On Debian use `sudo apt install libsdl2-dev`
