### ISSUE TITLE
Shader effect not reflected in canvas.into_inner()

### ISSUE THREAD

**Issue by SuperCuber** [ggez/ggez#444]
# Attempt at explaining the issue
I couldn't quite make a working minimal example so this is my attempt at explaining the issue.
This code:
```rust
let canvas = Canvas::new(...);
graphics::set_canvas(ctx, Some(&canvas));
let _lock = graphics::use_shader(ctx, shader);
shader.send(ctx, self.to_data())?;
graphics::rectangle(
    ctx,
    graphics::DrawMode::Fill,
    graphics::Rect { the whole screen },
    )?;
graphics::set_canvas(ctx, None);
```
Is supposed to include the post-shader image inside `canvas`. However, in the latest version, `canvas.into_inner().to_rgba8` returns all black (pre-shader image?) while `graphics::draw` displays the post-shader image.

# Where I actually found the bug
(in case you cannot reproduce it based on the information above)

You can see the difference between the behaviours by checking out [this commit](https://github.com/SuperCuber/mandelsaver/commit/48b0494741d37b57b98ed784fbff9f3c3317e9ae) on my project - it should work correctly, displaying a mandelbrot set and zooming into a random point on the edge of the shape, however if you `cargo update` you will see that it will zoom onto a random point on the screen.

I tracked the bug into a [single point](https://github.com/SuperCuber/mandelsaver/blob/48b0494741d37b57b98ed784fbff9f3c3317e9ae/src/implementation.rs#L77), which for completeness purposes I will include here.

```rust
    fn render(
        &mut self,
        shader: &graphics::Shader<AdditionalData>,
        ctx: &mut Context,
    ) -> GameResult<()> {
        let canvas = graphics::Canvas::new(
            ctx,
            SCREEN_RESOLUTION.0 as u32,
            SCREEN_RESOLUTION.1 as u32,
            NumSamples::One,
        )?;
        graphics::set_canvas(ctx, Some(&canvas));

        {
            let _lock = graphics::use_shader(ctx, shader);
            shader.send(ctx, self.to_data())?;
            graphics::rectangle(
                ctx,
                graphics::DrawMode::Fill,
                graphics::Rect {
                    x: 0.0,
                    y: 0.0,
                    w: SCREEN_RESOLUTION.0 as f32,
                    h: SCREEN_RESOLUTION.1 as f32,
                },
            )?;
        }

        graphics::set_canvas(ctx, None);

        self.cache = Some(canvas.into_inner());
        Ok(())
}
```

Later in the code this cache is drawn to the screen using 
```rust
        graphics::draw(
            ctx,
            self.cache.as_ref().expect("cache exists after render"),
            Point2::new(0.0, 0.0),
            0.0,
)
```
Which works correctly and includes the shader effect, however in the latest version, doing `canvas.into_inner().as_u8()` in [here](https://github.com/SuperCuber/mandelsaver/blob/48b0494741d37b57b98ed784fbff9f3c3317e9ae/src/implementation.rs#L133) gives an array of 0s, corresponding to the black rectangle drawn before.

I tried making a minimal example of the behavior but didn't quite succeed... I hope this issue makes sense, if you have any questions you're welcome to ask and I will try to elaborate further

**Comment by icefoxen** [comment]
Thanks, I'll see if I can reproduce this probably in a few days.  :heart:

**Comment by icefoxen** [comment]
Okay.  Tried this on my laptop (Debian Linux, Intel GPU) and I don't reproduce the bug, but do get a panic when the program starts to zoom:

```
thread 'main' panicked at 'Error InvalidOperation executing command: CopyTextureToBuffer(TextureCopyRegion { texture: Texture(3), kind: D2(1920, 1080, Single), cube_face: None, info: ImageInfoCommon { xoffset: 0, yoffset: 0, zoffset: 0, width: 1920, height: 1080, depth: 0, format: Format(R8_G8_B8_A8, Uint), mipmap: 0 } }, 9, 0, 2)', /home/icefox/.cargo/registry/src/github.com-1ecc6299db9ec823/gfx_device_gl-0.15.3/src/lib.rs:816:13
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:463
   5: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:350
   6: gfx_device_gl::Device::process
             at /home/icefox/.cargo/registry/src/github.com-1ecc6299db9ec823/gfx_device_gl-0.15.3/src/lib.rs:816
   7: gfx_device_gl::Device::no_fence_submit
             at /home/icefox/.cargo/registry/src/github.com-1ecc6299db9ec823/gfx_device_gl-0.15.3/src/lib.rs:823
   8: <gfx_device_gl::Device as gfx_core::Device>::submit
             at /home/icefox/.cargo/registry/src/github.com-1ecc6299db9ec823/gfx_device_gl-0.15.3/src/lib.rs:945
   9: <gfx::encoder::Encoder<R, C>>::flush_no_reset
             at /home/icefox/.cargo/registry/src/github.com-1ecc6299db9ec823/gfx-0.17.1/src/encoder.rs:197
  10: <gfx::encoder::Encoder<R, C>>::flush
             at /home/icefox/.cargo/registry/src/github.com-1ecc6299db9ec823/gfx-0.17.1/src/encoder.rs:188
  11: <ggez::graphics::image::ImageGeneric<gfx_device_gl::Resources>>::to_rgba8
             at /home/icefox/.cargo/registry/src/github.com-1ecc6299db9ec823/ggez-0.4.3/src/graphics/image.rs:117
  12: mandelbrot::implementation::select_zoom_position_screen
             at src/implementation.rs:132
  13: mandelbrot::implementation::update
             at src/implementation.rs:177
  14: <mandelbrot::MainState as ggez::event::EventHandler>::update
             at src/main.rs:43
  15: ggez::event::run
             at /home/icefox/.cargo/registry/src/github.com-1ecc6299db9ec823/ggez-0.4.3/src/event.rs:281
  16: mandelbrot::main
             at src/main.rs:103
  17: std::rt::lang_start::{{closure}}
             at /checkout/src/libstd/rt.rs:74
  18: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  19: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:105
  20: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:374
             at libstd/rt.rs:58
  21: std::rt::lang_start
             at /checkout/src/libstd/rt.rs:74
  22: main
  23: __libc_start_main
  24: _start
```

So I suspect that either we're doing something wrong or gfx-rs is doing something wrong (probably us) in terms of the texture copy when pulling the texture out of the canvas.  I would bet your graphics drivers are just not reporting the error properly but soldiering along trying to do the best they can.  What OS and GPU are you using?

Will try this on other platforms and see what happens.

**Comment by icefoxen** [comment]
Same error on Linux using NVidia proprietary drivers.

**Comment by icefoxen** [comment]
On Windows using AMD drivers, even the original program that works on Linux panics with an error:

```
    Finished dev [unoptimized + debuginfo] target(s) in 0.34s
     Running `target\debug\mandelbrot.exe`
thread 'main' panicked at 'main state: VideoError("Error constructing pipeline!\nThis should probably not be happening; it probably means an error in a shader or something.\nError was: DescriptorInit(ConstantBuffer(\"AdditionalData\", Some(Offset { name: \"size\", shader_offset: 16, code_offset: 8 })))")', libcore\result.rs:945:5
stack backtrace:
   0: std::sys::windows::backtrace::unwind_backtrace
             at C:\projects\rust\src\libstd\sys\windows\backtrace\mod.rs:65
   1: std::sys_common::backtrace::_print
             at C:\projects\rust\src\libstd\sys_common\backtrace.rs:71
   2: std::sys_common::backtrace::print
             at C:\projects\rust\src\libstd\sys_common\backtrace.rs:59
   3: std::panicking::default_hook::{{closure}}
             at C:\projects\rust\src\libstd\panicking.rs:211
   4: std::panicking::default_hook
             at C:\projects\rust\src\libstd\panicking.rs:227
   5: std::panicking::rust_panic_with_hook
             at C:\projects\rust\src\libstd\panicking.rs:463
   6: std::panicking::begin_panic_fmt
             at C:\projects\rust\src\libstd\panicking.rs:350
   7: std::panicking::rust_begin_panic
             at C:\projects\rust\src\libstd\panicking.rs:328
   8: core::panicking::panic_fmt
             at C:\projects\rust\src\libcore\panicking.rs:71
   9: core::result::unwrap_failed<ggez::error::GameError>
             at C:\projects\rust\src\libcore\macros.rs:26
  10: core::result::Result<mandelbrot::MainState, ggez::error::GameError>::expect<mandelbrot::MainState,ggez::error::GameError>
             at C:\projects\rust\src\libcore\result.rs:809
  11: mandelbrot::main
             at .\src\main.rs:101
  12: std::rt::lang_start::{{closure}}<()>
             at C:\projects\rust\src\libstd\rt.rs:74
  13: std::rt::lang_start_internal::{{closure}}
             at C:\projects\rust\src\libstd\rt.rs:59
  14: std::panicking::try::do_call<closure,i32>
             at C:\projects\rust\src\libstd\panicking.rs:310
  15: panic_unwind::__rust_maybe_catch_panic
             at C:\projects\rust\src\libpanic_unwind\lib.rs:105
  16: std::panicking::try
             at C:\projects\rust\src\libstd\panicking.rs:289
  17: std::panic::catch_unwind
             at C:\projects\rust\src\libstd\panic.rs:374
  18: std::rt::lang_start_internal
             at C:\projects\rust\src\libstd\rt.rs:58
  19: std::rt::lang_start<()>
             at C:\projects\rust\src\libstd\rt.rs:74
  20: main
  21: invoke_main
             at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  22: __scrt_common_main_seh
             at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:283
  23: BaseThreadInitThunk
  24: RtlUserThreadStart
error: process didn't exit successfully: `target\debug\mandelbrot.exe` (exit code: 101)
```

After running `cargo update` it still panics with the same error.

Hmmmm.

**Comment by SuperCuber** [comment]
Program runs for me on Windows 10 64bit with gtx 1060 gpu

**Comment by IGBC** [comment]
> doing `canvas.into_inner().as_u8()` in [here](https://github.com/SuperCuber/mandelsaver/blob/48b0494741d37b57b98ed784fbff9f3c3317e9ae/src/implementation.rs#L133) gives an array of 0s, corresponding to the black rectangle drawn before.

This looks like its related to #813 Which has been (mostly) fixed. This should be re-tested to check it still exists but without a code snippet that can reproduce the issue not sure what we can do about it. @SuperCuber are you able to provide a compete demo of the bug?

**Comment by SuperCuber** [comment]
@IGBC I haven't really touched that project since opening this issue... It seems to not compile anymore :/ 
So much for Cargo.locks working forever...

Not even my code that isn't compiling, it's `nalgebra-0.14.4` that's causing an issue. Updating an edition doesn't work, and even `cargo update` doesn't help...
I don't think I can reproduce the original issue, and updating to latest `ggez` would need me to change a bunch of code I guess.

The issue you linked seems very similar though

**Comment by IGBC** [comment]
I am going to call this closed, and we will keep an eye out for it cropping up in a 0.6 project.
