### ISSUE TITLE
graphics::image::encode panics

### ISSUE THREAD

**Issue by Bunogi** [ggez/ggez#463]
# Minimal Example
```rust
extern crate ggez;
use ggez::*;

fn main() {
    let c = conf::Conf::new();
    let ctx = &mut Context::load_from_conf("test_app", "Bunogi", c).unwrap();
    let img = graphics::Image::solid(ctx, 300, graphics::Color::new(1.0, 0.0, 0.0, 1.0)).unwrap();
    img.encode(ctx, graphics::ImageFormat::Png, "test.png").unwrap();
}
```
This code causes a panic with the following backtrace:
```
    Finished dev [unoptimized + debuginfo] target(s) in 0.11s
     Running `/tmp/imagetest/target/debug/imagetest`
thread 'main' panicked at 'Error InvalidOperation executing command: CopyTextureToBuffer(TextureCopyRegion { texture: Texture(3), kind: D2(300, 300, Single), cube_face: None, info: ImageInfoCommon { xoffset: 0, yoffset: 0, zoffset: 0, width: 300, height: 300, depth: 0, format: Format(R8_G8_B8_A8, Uint), mipmap: 0 } }, 6, 0, 2)', /home/bunogi/.cargo/registry/src/github.com-1ecc6299db9ec823/gfx_device_gl-0.15.3/src/lib.rs:816:13
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:475
   5: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:390
   6: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:345
   7: gfx_device_gl::Device::process
             at /home/bunogi/.cargo/registry/src/github.com-1ecc6299db9ec823/gfx_device_gl-0.15.3/src/lib.rs:816
   8: gfx_device_gl::Device::no_fence_submit
             at /home/bunogi/.cargo/registry/src/github.com-1ecc6299db9ec823/gfx_device_gl-0.15.3/src/lib.rs:823
   9: <gfx_device_gl::Device as gfx_core::Device>::submit
             at /home/bunogi/.cargo/registry/src/github.com-1ecc6299db9ec823/gfx_device_gl-0.15.3/src/lib.rs:945
  10: <gfx::encoder::Encoder<R, C>>::flush_no_reset
             at /home/bunogi/.cargo/registry/src/github.com-1ecc6299db9ec823/gfx-0.17.1/src/encoder.rs:197
  11: <gfx::encoder::Encoder<R, C>>::flush
             at /home/bunogi/.cargo/registry/src/github.com-1ecc6299db9ec823/gfx-0.17.1/src/encoder.rs:188
  12: <ggez::graphics::image::ImageGeneric<gfx_device_gl::Resources>>::to_rgba8
             at /home/bunogi/.cargo/registry/src/github.com-1ecc6299db9ec823/ggez-0.4.3/src/graphics/image.rs:117
  13: <ggez::graphics::image::ImageGeneric<gfx_device_gl::Resources>>::encode
             at /home/bunogi/.cargo/registry/src/github.com-1ecc6299db9ec823/ggez-0.4.3/src/graphics/image.rs:145
  14: imagetest::main
             at src/main.rs:8
  15: std::rt::lang_start::{{closure}}
             at /checkout/src/libstd/rt.rs:74
  16: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  17: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:105
  18: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:392
             at libstd/rt.rs:58
  19: std::rt::lang_start
             at /checkout/src/libstd/rt.rs:74
  20: main
  21: __libc_start_main
  22: _start
```

Using ggez 0.4.3, happens on both rust nightly 1.30.0 and rust stable 1.28.0.

**Comment by Bunogi** [comment]
I'm running arch linux with the amdgpu driver on an RX 480, kernel version 4.18.1.

**Comment by icefoxen** [comment]
The test program also fails on my Linux machine with an NVidia GPU and driver.  Same message and backtrace.

**Comment by PSteinhaus** [comment]
Fixed in current devel. Tested with this code:
```rust
fn main() {
    let cb = ggez::ContextBuilder::new("test_app", "Bunogi");
    let (mut ctx, event_loop) = cb.build().unwrap();
    let img = graphics::Image::solid(&mut ctx, 300, graphics::Color::new(1.0, 0.0, 0.0, 1.0)).unwrap();
    img.encode(&mut ctx, graphics::ImageFormat::Png, "/test.png").unwrap();
}
```
