### ISSUE TITLE
crash on using DrawMode::Fill

### ISSUE THREAD

**Issue by InfraOrder** [ggez/ggez#470]
Hi, having a lot of fun with your ggez.
I have been playing around with a super shape formula and came across an issue with DrawMode::Fill.

basically using Line instead of Fill the application runs perfect. However as soon as Fill is used the application panics.

Here's the code (sorry it is a bit messy):
```
extern crate ggez;
    
use ggez::ContextBuilder;
use ggez::conf;
use ggez::event;
use ggez::Context;
use ggez::GameResult;

use ggez::graphics::{clear, Color, set_background_color, present, set_color, circle, DrawMode, Point2, polygon, 
    set_screen_coordinates, Rect,
};
use ggez::mouse::{MouseContext, get_position};

use std::f64::consts::PI;

fn main() {
    let cb = ContextBuilder::new("super_shapes", "nate")
    .window_setup(conf::WindowSetup::default()
    .title("super_shapes"))
    .window_mode(conf::WindowMode::default()
    // .fullscreen_type(conf::FullscreenType::Desktop)
    // .dimensions(1920, 1080));
    .dimensions(800, 800));
    let ctx = &mut cb.build().unwrap();
    let state = &mut Window::new(ctx).unwrap();
    event::run(ctx, state).unwrap();
}

fn formula(z: f32) -> (f32, f32) {
	let x = z;
	let y = z * z;
	(x, y)
}

struct Window {	
    width: u32,
    height: u32,
    shapes: Vec<Shape>,
    t: f32,
    a: f32,
    b: f32,
    m: f32,
    n1: f32,
    n2: f32,
    n3: f32,
}

struct Shape {
    points: Vec<Point2>,
    color: Color,
}

fn r(theta: f32, a: f32, b: f32, m: f32, n1: f32, n2: f32, n3: f32) -> f32 {
    ((((m * theta / 4.0).cos() / a).abs().powf(n2)) + 
     (((m * theta / 4.0).sin() / b).abs().powf(n3))).powf(-1.0 / n1)
}

impl Window {
	pub fn new(ctx: &mut Context) -> GameResult<Window> {
		let BLACK = Color::new(0.0, 0.0, 0.0, 1.0);
		set_background_color(ctx, BLACK);

		let width = ctx.conf.window_mode.width;
		let height = ctx.conf.window_mode.height;
        
        set_screen_coordinates(ctx, Rect::new(
            -(width as f32 / 4.0), 
            -(height as f32 / 4.0), 
            width as f32 / 2.0, 
            width as f32 / 2.0,
        )).unwrap();

        let mouse = MouseContext::new();

        let mut shapes = Vec::new();
        // shapes.push(Shape{points: Vec::new(), color: Color::new(1.0, 1.0, 1.0, 1.0)});
        let iter = 4;
        for i in 0..iter {
            let c = ((i as f32 - 0.0) * ((0.0 - 1.0) / ((iter - 1) as f32 - 0.0))) + 1.0;
            shapes.push(Shape{
                points: Vec::new(),
                color: Color::new(c, c, c, 1.0),
            })
        }

		Ok(Window{
			width: width,
			height: height,
                        shapes: shapes,
                        t: 0.0,
                        a: 2.0,
                        b: 2.0,
                        m: 6.0,
                        n1: 1.0,
                        n2: 1.0,
                        n3: 1.0,       
		})
	}
}

impl event::EventHandler for Window {
	fn update(&mut self, ctx: &mut Context) -> GameResult<()> {
        let mouse_pos_x = get_position(ctx).unwrap()[0];
        let mouse_pos_y = get_position(ctx).unwrap()[1];
        let var = 1.0;
        let var_2 = 2.0;
        let var_3 = 10.0;
        self.n1 = (self.t.cos() * var) + var;
        self.n2 = (self.t.sin() * var_2) + var_2;
        self.n3 = ((self.t.tan()) + var) + var;

	// wanting to create something that plots out points of a graph
        let mut pos = Vec::new();
        let iter = 100;
        for i in 0..iter {
            let old_range = (iter -1) as f32 - 0.0;
            let new_range = ((2.0 * PI) - 0.0) as f32;
            let theta = ((i as f32 - 0.0) * (new_range / old_range)) + 0.0;
            let rad = r(theta, self.a, self.b, self.m, self.n1, self.n2, self.n3);
            let mut x = rad * theta.cos() * 50.0;
            let mut y = rad * theta.sin() * 50.0;
            pos.push(Point2::new(x, y));
        }
        self.shapes[0].points = pos;

        for i in 1..self.shapes.len() {
            let mut new_point = Vec::new();
            for point in &self.shapes[i - 1].points {
               let x = point[0];
               let y = point[1];
               let new_x = 2.0 * x;
               let new_y = 2.0 * y;
               new_point.push(Point2::new(new_x, new_y));
            }
            self.shapes[i].points = new_point;
        }

        self.t += 0.1;
		Ok(())
	}
	fn draw(&mut self, ctx: &mut Context) -> GameResult<()> {
		clear(ctx);
        
        for i in (0..self.shapes.len()).rev() {
            set_color(ctx, self.shapes[i].color).unwrap();
            // polygon(ctx, DrawMode::Line(1.0), &self.shapes[i].points).unwrap();
            polygon(ctx, DrawMode::Fill, &self.shapes[i].points).unwrap();
        }

		present(ctx);
		Ok(())
	}
}
```

the error I get is:
thread 'main' panicked at 'attempt to subtract with overflow', /home/nate/.cargo/registry/src/github.com-1ecc6299db9ec823/lyon_tessellation-0.10.2/src/fixed.rs:245:33
note: Run with `RUST_BACKTRACE=1` for a backtrace.

any idea how I can fix this issue. Thank you very much.

**Comment by icefoxen** [comment]
Thank you!  I'm able to reproduce the bug.  (Also the line version of the program looks really cool!)

The full backtrace I get is this:

```
thread 'main' panicked at 'attempt to subtract with overflow', /home/icefox/.cargo/registry/src/github.com-1ecc6299db9ec823/lyon_tessellation-0.10.2/src/fixed.rs:245:33
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:511
   5: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:426
   6: rust_begin_unwind
             at libstd/panicking.rs:337
   7: core::panicking::panic_fmt
             at libcore/panicking.rs:92
   8: core::panicking::panic
             at libcore/panicking.rs:53
   9: <lyon_tessellation::fixed::Fp32<F> as core::ops::arith::Sub>::sub
             at /home/icefox/.cargo/registry/src/github.com-1ecc6299db9ec823/lyon_tessellation-0.10.2/src/fixed.rs:245
  10: <euclid::point::TypedPoint2D<T, U> as core::ops::arith::Sub>::sub
             at /home/icefox/.cargo/registry/src/github.com-1ecc6299db9ec823/euclid-0.17.3/src/point.rs:176
  11: lyon_tessellation::path_fill::FillTessellator::tessellator_loop
             at /home/icefox/.cargo/registry/src/github.com-1ecc6299db9ec823/lyon_tessellation-0.10.2/src/path_fill.rs:431
  12: lyon_tessellation::path_fill::FillTessellator::tessellate_events
             at /home/icefox/.cargo/registry/src/github.com-1ecc6299db9ec823/lyon_tessellation-0.10.2/src/path_fill.rs:352
  13: lyon_tessellation::path_fill::FillTessellator::tessellate_path
             at /home/icefox/.cargo/registry/src/github.com-1ecc6299db9ec823/lyon_tessellation-0.10.2/src/path_fill.rs:327
  14: lyon_tessellation::basic_shapes::fill_polyline
             at /home/icefox/.cargo/registry/src/github.com-1ecc6299db9ec823/lyon_tessellation-0.10.2/src/basic_shapes.rs:820
  15: ggez::graphics::mesh::MeshBuilder::polygon
             at /home/icefox/.cargo/registry/src/github.com-1ecc6299db9ec823/ggez-0.4.4/src/graphics/mesh.rs:205
  16: ggez::graphics::mesh::Mesh::new_polygon
             at /home/icefox/.cargo/registry/src/github.com-1ecc6299db9ec823/ggez-0.4.4/src/graphics/mesh.rs:355
  17: ggez::graphics::polygon
             at /home/icefox/.cargo/registry/src/github.com-1ecc6299db9ec823/ggez-0.4.4/src/graphics/mod.rs:454
  18: <fillcrash::Window as ggez::event::EventHandler>::draw
             at src/main.rs:147
  19: ggez::event::run
             at /home/icefox/.cargo/registry/src/github.com-1ecc6299db9ec823/ggez-0.4.4/src/event.rs:282
  20: fillcrash::main
             at src/main.rs:26
  21: std::rt::lang_start::{{closure}}
             at /checkout/src/libstd/rt.rs:74
  22: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  23: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:105
  24: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:392
             at libstd/rt.rs:58
  25: std::rt::lang_start
             at /checkout/src/libstd/rt.rs:74
  26: main
  27: __libc_start_main
  28: _start
```

Running in release mode means it won't check for overflow/underflow, but the program still panics with this result:

```
thread 'main' panicked at 'Could not fill polygon?: Internal(E01)', libcore/result.rs:945:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:511
   5: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:426
   6: rust_begin_unwind
             at libstd/panicking.rs:337
   7: core::panicking::panic_fmt
             at libcore/panicking.rs:92
   8: core::result::unwrap_failed
   9: ggez::graphics::mesh::MeshBuilder::polygon
  10: ggez::graphics::mesh::Mesh::new_polygon
  11: ggez::graphics::polygon
  12: <fillcrash::Window as ggez::event::EventHandler>::draw
  13: ggez::event::run
  14: fillcrash::main
  15: std::rt::lang_start::{{closure}}
  16: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  17: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:105
  18: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:392
             at libstd/rt.rs:58
  19: main
  20: __libc_start_main
  21: _start
```

Either way the crash is happening in lyon, the crate that ggez uses for shape tesselation. The current released version of ggez uses lyon 0.10, while the most recent version is 0.11, so I tried updating lyon but got the same crashes with both versions.

What I *suspect* is happening is that you are somehow creating a shape that can't be filled by whatever algorithm lyon is using; maybe it is self-intersecting in weird ways?  I will open an issue with lyon and we can probably get a better answer soon.

**Comment by InfraOrder** [comment]
Thank you for the response, glad to help.

**Comment by robojumper** [comment]
Sounds like a somewhat simple case of "number too big": [The documentation](https://docs.rs/lyon_tessellation/0.10.2/lyon_tessellation/struct.FillTessellator.html#limitations) has to say the following:

> # Limitations
> The fill tessellator internally works with 16.16 fixed point numbers. This means that it is unable to represent numbers with absolute values larger than 32767.0 without running into overflows and undefined behavior.

Though I haven't investigated it, the example seems to create some pretty big numbers, and the stack trace lines up.

**Comment by InfraOrder** [comment]
Thanks!! thought it might be something to do with that. will ensure numbers in future don't get as big as this.

**Comment by InfraOrder** [comment]
Hi, good morning. Sorry for this but, after adding a simple restriction for the x and y values the problem still persists.

```
extern crate ggez;
    
use ggez::ContextBuilder;
use ggez::conf;
use ggez::event;
use ggez::Context;
use ggez::GameResult;

use ggez::graphics::{clear, Color, set_background_color, present, set_color, circle, DrawMode, Point2, polygon, 
    set_screen_coordinates, Rect,
};
use ggez::mouse::{MouseContext, get_position};

use std::f64::consts::PI;

fn main() {
	let cb = ContextBuilder::new("super_shapes", "nate")
    .window_setup(conf::WindowSetup::default()
  	.title("super_shapes"))
    .window_mode(conf::WindowMode::default()
    // .fullscreen_type(conf::FullscreenType::Desktop)
  	// .dimensions(1920, 1080));
  	.dimensions(800, 800));
    let ctx = &mut cb.build().unwrap();
    let state = &mut Window::new(ctx).unwrap();
    event::run(ctx, state).unwrap();
}

struct Window {	
	width: u32,
	height: u32,
    shapes: Vec<Shape>,
    t: f32,
    a: f32,
    b: f32,
    m: f32,
    n1: f32,
    n2: f32,
    n3: f32,
}

#[derive(Clone)]
struct Shape {
    points: Vec<Point2>,
    color: Color,
}

fn r(theta: f32, a: f32, b: f32, m: f32, n1: f32, n2: f32, n3: f32) -> f32 {
    ((((m * theta / 4.0).cos() / a).abs().powf(n2)) + 
     (((m * theta / 4.0).sin() / b).abs().powf(n3))).powf(-1.0 / n1)
}

impl Window {
	pub fn new(ctx: &mut Context) -> GameResult<Window> {
		let BLACK = Color::new(0.0, 0.0, 0.0, 1.0);
		set_background_color(ctx, BLACK);

		let width = ctx.conf.window_mode.width;
		let height = ctx.conf.window_mode.height;
        
        set_screen_coordinates(ctx, Rect::new(
            -(width as f32 / 4.0), 
            -(height as f32 / 4.0), 
            width as f32 / 2.0, 
            width as f32 / 2.0,
        )).unwrap();

        let mouse = MouseContext::new();

        let mut shapes = Vec::new();
        // shapes.push(Shape{points: Vec::new(), color: Color::new(1.0, 1.0, 1.0, 1.0)});
        let iter = 4;
        for i in 0..iter {
            let c = ((i as f32 - 0.0) * ((0.0 - 1.0) / ((iter - 1) as f32 - 0.0))) + 1.0;
            shapes.push(Shape{
                points: Vec::new(),
                color: Color::new(c, c, c, 1.0),
            })
        }

		Ok(Window{
			width: width,
			height: height,
            shapes: shapes,
            t: 0.0,
            a: 2.0,
            b: 2.0,
            m: 6.0,
            n1: 1.0,
            n2: 1.0,
            n3: 1.0,       
		})
	}
}

impl event::EventHandler for Window {
	fn update(&mut self, ctx: &mut Context) -> GameResult<()> {
        let mouse_pos_x = get_position(ctx).unwrap()[0];
        let mouse_pos_y = get_position(ctx).unwrap()[1];
        let var = 1.0;
        let var_2 = 2.0;
        let var_3 = 10.0;
        self.n1 = (self.t.cos() * var) + var;
        self.n2 = (self.t.sin() * var_2) + var_2;
        self.n3 = ((self.t.tan()) + var) + var;

		// wanting to create something that plots out points of a graph
        let mut pos = Vec::new();
        let iter = 100;
        for i in 0..iter {
            let old_range = (iter -1) as f32 - 0.0;
            let new_range = ((2.0 * PI) - 0.0) as f32;
            let theta = ((i as f32 - 0.0) * (new_range / old_range)) + 0.0;
            let rad = r(theta, self.a, self.b, self.m, self.n1, self.n2, self.n3);
            let mut x = rad * theta.cos() * 50.0;
            let mut y = rad * theta.sin() * 50.0;

            // simple if functions to restrict x and y
            if x > (self.width / 2) as f32 { x = (self.width / 2) as f32 }
            else if x < -((self.width / 2) as f32) { x = -((self.width / 2) as f32) }
            if y > (self.height / 2) as f32 { y = (self.height / 2) as f32 }
            else if y < -((self.height / 2) as f32) { y = -((self.height / 2) as f32) }

            pos.push(Point2::new(x, y));
        }
        self.shapes[0].points = pos;

        for i in 1..self.shapes.len() {
            let mut new_point = Vec::new();
            for point in &self.shapes[i - 1].points {
                let x = point[0];
                let y = point[1];
                let mut new_x = 2.0 * x;
                let mut new_y = 2.0 * y;

                // simple if functions to restrict x and y
                if new_x > (self.width / 2) as f32 { new_x = (self.width / 2) as f32 }
                else if new_x < -((self.width / 2) as f32) { new_x = -((self.width / 2) as f32) }
                if new_y > (self.height / 2) as f32 { new_y = (self.height / 2) as f32 }
                else if new_y < -((self.height / 2) as f32) { new_y = -((self.height / 2) as f32) }

                println!("x is {}, y is {}", x, y);

                new_point.push(Point2::new(new_x, new_y));
            }
            self.shapes[i].points = new_point;
        }

        self.t += 0.1;
		Ok(())
	}
	fn draw(&mut self, ctx: &mut Context) -> GameResult<()> {
		clear(ctx);
        
        for i in (0..self.shapes.len()).rev() {
            set_color(ctx, self.shapes[i].color).unwrap();
            // polygon(ctx, DrawMode::Line(1.0), &self.shapes[i].points).unwrap();
            polygon(ctx, DrawMode::Fill, &self.shapes[i].points).unwrap();
        }

		present(ctx);
		Ok(())
	}
}

```

**Comment by robojumper** [comment]
Looks like you're passing [`NaN`](https://doc.rust-lang.org/std/f32/constant.NAN.html) to the function at some point, which probably breaks that algorithm too. You can verify this with the following code:
```diff
    for i in (0..self.shapes.len()).rev() {
        set_color(ctx, self.shapes[i].color).unwrap();
        // polygon(ctx, DrawMode::Line(1.0), &self.shapes[i].points).unwrap();
+       if self.shapes[i].points.iter().any(|p| p[0].is_nan() || p[1].is_nan()) {
+           println!("Warning, we have an NAN. This will probably crash!");
+       }
        polygon(ctx, DrawMode::Fill, &self.shapes[i].points).unwrap();
+       println!("##########");
    }
```
---------------
    ##########
    ##########
    ##########
    ##########
    Warning, we have an NAN. This will probably crash!
    thread 'main' panicked at 'attempt to subtract with overflow'

**Comment by InfraOrder** [comment]
thanks, will have a look again through the code.. Do you know what could be causing a nan value to be generated?

**Comment by InfraOrder** [comment]
just a quick fix, added this to the initial generation of x and y:
 
```
// simple if functions to restrict x and y
if x > (self.width / 2) as f32 || x.is_nan() { x = (self.width / 2) as f32 }
else if x < -((self.width / 2) as f32) { x = -((self.width / 2) as f32) }
if y > (self.height / 2) as f32 || y.is_nan() { y = (self.height / 2) as f32 }
else if y < -((self.height / 2) as f32) { y = -((self.height / 2) as f32) }
```

working without a crash now. thanks again!

**Comment by icefoxen** [comment]
Making numbers too big should create Inf or -Inf, afaik. NaN comes from operations with no meaning such as 0/0 or Inf/Inf. Rust is pretty straightforward in conforming to IEEE754 like most floating point implementations.

**Comment by nical** [comment]
Lyon author here. The current limitation on the size of the shapes is unfortunate, and I'm working on lifting it but it will take a while before I finish it.
As far as NaNs go, they totally break the tessellator, and there's no validation for that currently. I think that it is most appropriate to check that the input path doesn't contain NaNs before running the algorithm since there isn't an obvious way for the tessellator to work around them (granted it could report a better error).
