### ISSUE TITLE
OpenGlVersionNotSupported with OpenGL 3.2/3.3

### ISSUE THREAD

**Issue by sarna** [ggez/ggez#626]
Hi!

When running the [context example from Hello ggez](https://github.com/ggez/ggez/blob/master/docs/guides/HelloGgez.md#context) I'm getting this error:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: WindowCreationError(OpenGlVersionNotSupported)', src/libcore/result.rs:999:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

`glxinfo | grep "OpenGL"` gives me
```
OpenGL vendor string: NVIDIA Corporation
OpenGL renderer string: GeForce GT 240/PCIe/SSE2
OpenGL core profile version string: 3.3.0 NVIDIA 340.107
OpenGL core profile shading language version string: 3.30 NVIDIA via Cg compiler
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 3.3.0 NVIDIA 340.107
OpenGL shading language version string: 3.30 NVIDIA via Cg compiler
OpenGL context flags: (none)
OpenGL profile mask: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 2.0 NVIDIA 340.107 340.107
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 1.00
OpenGL ES profile extensions:
```

My GPU is a [GeForce GT 240](https://www.geforce.com/hardware/desktop-gpus/geforce-gt-240/specifications), it says it supports OpenGL 3.2.

I tried setting the [backend](https://docs.rs/ggez/0.5.0-rc.2/ggez/struct.ContextBuilder.html#method.backend) to 3.3 and 3.2, didn't work. Lower versions didn't work either.

Rust backtrace:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: WindowCreationError(OpenGlVersionNotSupported)', src/libcore/result.rs:999:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:197
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:211
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:474
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:381
   6: rust_begin_unwind
             at src/libstd/panicking.rs:308
   7: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
   8: core::result::unwrap_failed
             at /rustc/8dd4aae9a83964cc08505da92d07ec68a3a2341d/src/libcore/macros.rs:18
   9: core::result::Result<T,E>::unwrap
             at /rustc/8dd4aae9a83964cc08505da92d07ec68a3a2341d/src/libcore/result.rs:800
  10: emu8::main
             at src/main.rs:22
  11: std::rt::lang_start::{{closure}}
             at /rustc/8dd4aae9a83964cc08505da92d07ec68a3a2341d/src/libstd/rt.rs:64
  12: std::panicking::try::do_call
             at src/libstd/rt.rs:49
             at src/libstd/panicking.rs:293
  13: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:85
  14: std::rt::lang_start_internal
             at src/libstd/panicking.rs:272
             at src/libstd/panic.rs:388
             at src/libstd/rt.rs:48
  15: std::rt::lang_start
             at /rustc/8dd4aae9a83964cc08505da92d07ec68a3a2341d/src/libstd/rt.rs:64
  16: main
  17: __libc_start_main
  18: _start
```

My setup:
GPU: [Nvidia GeForce GT 240](https://www.geforce.com/hardware/desktop-gpus/geforce-gt-240/specifications)
Drivers: version 340.107 from nvidia-349 (proprietary, tested)
OS: Ubuntu LTS 18.04
WM: Gnome

Thanks for working on that awesome library!

**Comment by icefoxen** [comment]
Well that ain't right.  Thanks for the bug report!  Are you using the latest git checkout?  If so, have you tried the devel branch?  I don't THINK it will make any difference but you never know...

Let's see... the error is *probably* coming from [here](https://github.com/ggez/ggez/blob/508c0e664a3082bd327230a0af96a5270e2b576d/src/graphics/context.rs#L145) since that's where the window actually gets built, which calls [`Backend::init()`](https://github.com/ggez/ggez/blob/508c0e664a3082bd327230a0af96a5270e2b576d/src/graphics/mod.rs#L230).  If you print out the ` glutin::ContextBuilder` within the `init()` function we can double check that what it's asking for is actually what we want.

Apart from that I'm not entirely sure what might be going on though.  We may have to punt this upstream to `glutin` or `gfx_backend_glutin` and see what they say.

**Comment by icefoxen** [comment]
That's weird.  Though, per [the docs](https://docs.rs/glutin/0.20.0/glutin/struct.ContextBuilder.html), it just has two members that are public and both of those implement `Debug`.  Just print those out separately.

**Comment by sarna** [comment]
Hmm, weird. It prints `Specific(OpenGl, (2, 4))` :thinking:

**Comment by icefoxen** [comment]
Heckin' weird.  It's kinda a long shot, but try playing with the [samples or srgb settings](https://docs.rs/ggez/0.5.0-rc.2/ggez/conf/struct.WindowSetup.html) in creating your context and see if those fix anything.

**Comment by sarna** [comment]
Tried changing these, no dice.

Full `glxinfo`:
[glxinfo.txt](https://github.com/ggez/ggez/files/3162893/glxinfo.txt)

**Comment by icefoxen** [comment]
I dunno what else to check then.  Everything looks like it should work as far as I can tell.  :disappointed:   The actual OpenGL context is created by [`glutin`](https://crates.io/crates/glutin) and so that's where the error is coming from, perhaps you can try with some of their examples?  If we can confirm that this bug occurs just in plain `glutin` then that's something.

**Comment by sarna** [comment]
Their examples.. don't work either.

They all panic on unimplemented:
```
sarna@ub:~/git/glutin$ RUST_BACKTRACE=1 cargo run --example window
    Finished dev [unoptimized + debuginfo] target(s) in 0.42s
     Running `target/debug/examples/window`
thread 'main' panicked at 'not yet implemented', glutin/src/api/egl/mod.rs:1044:35
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:197
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:211
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:474
   5: std::panicking::begin_panic
             at /rustc/8dd4aae9a83964cc08505da92d07ec68a3a2341d/src/libstd/panicking.rs:408
   6: glutin::api::egl::choose_fbconfig
             at glutin/src/api/egl/mod.rs:1044
   7: glutin::api::egl::Context::new
             at glutin/src/api/egl/mod.rs:435
   8: glutin::platform_impl::platform_impl::x11::Context::new_first_stage::{{closure}}
             at ./glutin/src/platform_impl/unix/x11.rs:370
   9: glutin::platform_impl::platform_impl::x11::Context::new_first_stage
             at ./glutin/src/platform_impl/unix/x11.rs:397
  10: glutin::platform_impl::platform_impl::x11::Context::new_impl
             at ./glutin/src/platform_impl/unix/x11.rs:486
  11: glutin::platform_impl::platform_impl::x11::Context::new::{{closure}}
             at ./glutin/src/platform_impl/unix/x11.rs:459
  12: glutin::platform_impl::platform_impl::x11::Context::try_then_fallback
             at ./glutin/src/platform_impl/unix/x11.rs:178
  13: glutin::platform_impl::platform_impl::x11::Context::new
             at ./glutin/src/platform_impl/unix/x11.rs:458
  14: glutin::platform_impl::platform_impl::Context::new_windowed
             at ./glutin/src/platform_impl/unix/mod.rs:115
  15: glutin::windowed::<impl glutin::ContextBuilder<T>>::build_windowed
             at ./glutin/src/windowed.rs:337
  16: window::main
             at glutin_examples/examples/window.rs:13
  17: std::rt::lang_start::{{closure}}
             at /rustc/8dd4aae9a83964cc08505da92d07ec68a3a2341d/src/libstd/rt.rs:64
  18: std::panicking::try::do_call
             at src/libstd/rt.rs:49
             at src/libstd/panicking.rs:293
  19: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:85
  20: std::rt::lang_start_internal
             at src/libstd/panicking.rs:272
             at src/libstd/panic.rs:388
             at src/libstd/rt.rs:48
  21: std::rt::lang_start
             at /rustc/8dd4aae9a83964cc08505da92d07ec68a3a2341d/src/libstd/rt.rs:64
  22: main
  23: __libc_start_main
  24: _start
```
The line's name? 
```rust
match (api, version) {
    (Api::OpenGlEs, Some((3, _))) => {
        // [...]
    }
    (Api::OpenGlEs, Some((2, _))) => {
        // [...]
    }
    (Api::OpenGlEs, Some((1, _))) => {
        // [...]
    }
    (Api::OpenGlEs, _) => unimplemented!(), // <-- this one
    // [...]
```
I tried printing `version` in this branch and it's.. `None`. I don't know what's happening. Should I open an issue in `glutin`?

**Comment by sarna** [comment]
After changing the example a bit (I added `with_gl(GlRequest::Specific(Api::OpenGl, (3, 3)))` to the `ContextBuilder`) I'm getting this:
```
sarna@ub:~/git/glutin$ RUST_BACKTRACE=1 cargo run --example window
   Compiling glutin_examples v0.1.2 (/home/sarna/git/glutin/glutin_examples)
    Finished dev [unoptimized + debuginfo] target(s) in 3.54s
     Running `target/debug/examples/window`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: CreationErrors([OpenGlVersionNotSupported, OpenGlVersionNotSupported])', src/libcore/result.rs:999:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:197
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:211
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:474
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:381
   6: rust_begin_unwind
             at src/libstd/panicking.rs:308
   7: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
   8: core::result::unwrap_failed
             at /rustc/8dd4aae9a83964cc08505da92d07ec68a3a2341d/src/libcore/macros.rs:18
   9: core::result::Result<T,E>::unwrap
             at /rustc/8dd4aae9a83964cc08505da92d07ec68a3a2341d/src/libcore/result.rs:800
  10: window::main
             at glutin_examples/examples/window.rs:16
  11: std::rt::lang_start::{{closure}}
             at /rustc/8dd4aae9a83964cc08505da92d07ec68a3a2341d/src/libstd/rt.rs:64
  12: std::panicking::try::do_call
             at src/libstd/rt.rs:49
             at src/libstd/panicking.rs:293
  13: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:85
  14: std::rt::lang_start_internal
             at src/libstd/panicking.rs:272
             at src/libstd/panic.rs:388
             at src/libstd/rt.rs:48
  15: std::rt::lang_start
             at /rustc/8dd4aae9a83964cc08505da92d07ec68a3a2341d/src/libstd/rt.rs:64
  16: main
  17: __libc_start_main
  18: _start
```
Also, same error after fiddling with gl profiles.

**Comment by icefoxen** [comment]
Whew.  Thank you for all your work!  I was about to say I'll boot the issue upstream to glutin, but... it appears you've already done that.  :heart: Sorry this has all been so intractable...  Supporting 10-year-old graphics hardware is hard work.
