### ISSUE TITLE
Panic in Canvas::new() on windows

### ISSUE THREAD

**Issue by sullyj3** [ggez/ggez#719]
**Describe the bug**

**To Reproduce**
```
impl Platformer {
    fn new(ctx: &mut Context) -> Platformer {
        // SNIP

        Platformer {
            // SNIP

            world_canvas: Canvas::new(ctx, 240, 160, ggez::conf::NumSamples::Zero)
                .expect("couldn't init world_canvas"),
            ui_canvas   : Canvas::new(ctx, 2206, 1504, ggez::conf::NumSamples::Zero)
                .expect("couldn't init ui_canvas"),
        }
    }
}
```
The panic is on the line starting with world_canvas (line 86, mentioned in the backtrace).

Backtrace:
```
PS C:\Users\James\Code\rust_platformer> $Env:RUST_BACKTRACE=1; cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.49s
     Running `target\debug\rust_platformer.exe`
thread 'main' panicked at 'Error InvalidValue creating texture: Info { kind: D2(240, 160, Multi(0)), levels: 1, format: R8_G8_B8_A8, bind: RENDER_TARGET | SHADER_RESOURCE | TRANSFER_SRC, usage: Data }, hint: Some(Srgb)', C:\Users\James\.cargo\registry\src\github.com-1ecc6299db9ec823\gfx_device_gl-0.16.2\src\factory.rs:449:13
stack backtrace:
   0: backtrace::backtrace::trace_unsynchronized
             at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.37\src\backtrace\mod.rs:66
   1: std::sys_common::backtrace::_print_fmt
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734\/src\libstd\sys_common\backtrace.rs:76
   2: std::sys_common::backtrace::_print::{{impl}}::fmt
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734\/src\libstd\sys_common\backtrace.rs:60
   3: core::fmt::write
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734\/src\libcore\fmt\mod.rs:1030
   4: std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734\/src\libstd\io\mod.rs:1412
   5: std::sys_common::backtrace::_print
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734\/src\libstd\sys_common\backtrace.rs:64
   6: std::sys_common::backtrace::print
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734\/src\libstd\sys_common\backtrace.rs:49
   7: std::panicking::default_hook::{{closure}}
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734\/src\libstd\panicking.rs:196
   8: std::panicking::default_hook
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734\/src\libstd\panicking.rs:210
   9: std::panicking::rust_panic_with_hook
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734\/src\libstd\panicking.rs:473
  10: std::panicking::continue_panic_fmt
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734\/src\libstd\panicking.rs:380
  11: std::panicking::begin_panic_fmt
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734\/src\libstd\panicking.rs:335
  12: gfx_device_gl::factory::{{impl}}::create_texture_raw
             at C:\Users\James\.cargo\registry\src\github.com-1ecc6299db9ec823\gfx_device_gl-0.16.2\src\factory.rs:449
  13: ggez::graphics::canvas::CanvasGeneric<ggez::graphics::GlBackendSpec>::new
             at C:\Users\James\.cargo\registry\src\github.com-1ecc6299db9ec823\ggez-0.5.1\src\graphics\canvas.rs:66
  14: rust_platformer::Platformer::new
             at .\src\main.rs:86
  15: rust_platformer::main
             at .\src\main.rs:485
  16: std::rt::lang_start::{{closure}}<()>
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734\src\libstd\rt.rs:64
  17: std::rt::lang_start_internal::{{closure}}
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734\/src\libstd\rt.rs:49
  18: std::panicking::try::do_call<closure-0,i32>
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734\/src\libstd\panicking.rs:292
  19: panic_unwind::__rust_maybe_catch_panic
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734\/src\libpanic_unwind\lib.rs:80
  20: std::panicking::try
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734\/src\libstd\panicking.rs:271
  21: std::panic::catch_unwind
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734\/src\libstd\panic.rs:394
  22: std::rt::lang_start_internal
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734\/src\libstd\rt.rs:48
  23: std::rt::lang_start<()>
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734\src\libstd\rt.rs:64
  24: main
  25: invoke_main
             at d:\agent\_work\3\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  26: __scrt_common_main_seh
             at d:\agent\_work\3\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  27: BaseThreadInitThunk
  28: RtlUserThreadStart
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: process didn't exit successfully: `target\debug\rust_platformer.exe` (exit code: 101)
```

Links to relevant code:
https://docs.rs/ggez/0.5.1/src/ggez/graphics/canvas.rs.html#66
https://docs.rs/gfx_device_gl/0.16.2/src/gfx_device_gl/factory.rs.html#449

**Expected behavior**

**Screenshots or pasted code**
If applicable, add screenshots etc to help explain your problem.

**Hardware and Software:**
 - ggez version: For example, release 0.4.4, current git master, current git devel branch, etc.
 - OS: For example, Windows 10, Linux (Debian 9), etc
 - Graphics card: For example, NVidia GTX 660, Intel Iris 520, etc.
 - Graphics card drivers: Whether you're using the vendor-provided drivers or open source, if applicable on your platform -- generally only relevant for Linux using NVidia hardware

**Comment by sullyj3** [comment]
Accidentally opened the same issue twice #720
