### ISSUE TITLE
Attempted to leave type uninitialized on nightly rust

### ISSUE THREAD

**Issue by Palladinium** [ggez/ggez#832]
**Describe the bug**
On nightly Rust, the following panic occurs almost immediately after starting up a game, as soon as the mouse cursor is on the window.

```
thread 'main' panicked at 'attempted to leave type `platform::platform::x11::util::input::PointerState` uninitialized, which is invalid', /home/patrick/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/mem/mod.rs:659:9
stack backtrace:
   0:     0x55a37d33d1b0 - std::backtrace_rs::backtrace::libunwind::trace::h303a626d53553a64
                               at /rustc/7bade6ef730cff83f3591479a98916920f66decd/library/std/src/../../backtrace/src/backtrace/libunwind.rs:100:5
   1:     0x55a37d33d1b0 - std::backtrace_rs::backtrace::trace_unsynchronized::h6abb882733c3f18c
                               at /rustc/7bade6ef730cff83f3591479a98916920f66decd/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55a37d33d1b0 - std::sys_common::backtrace::_print_fmt::h57829321f1d9217a
                               at /rustc/7bade6ef730cff83f3591479a98916920f66decd/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x55a37d33d1b0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h400b66a054640aac
                               at /rustc/7bade6ef730cff83f3591479a98916920f66decd/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x55a37d35de9c - core::fmt::write::h1857a60b204f1b6a
                               at /rustc/7bade6ef730cff83f3591479a98916920f66decd/library/core/src/fmt/mod.rs:1076:17
   5:     0x55a37d33a3e2 - std::io::Write::write_fmt::h6453b28c8b27c6ea
                               at /rustc/7bade6ef730cff83f3591479a98916920f66decd/library/std/src/io/mod.rs:1516:15
   6:     0x55a37d33f6f5 - std::sys_common::backtrace::_print::h15cc4b3923cc9bc0
                               at /rustc/7bade6ef730cff83f3591479a98916920f66decd/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x55a37d33f6f5 - std::sys_common::backtrace::print::h953c7be178c0674d
                               at /rustc/7bade6ef730cff83f3591479a98916920f66decd/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x55a37d33f6f5 - std::panicking::default_hook::{{closure}}::h635d667f571198f0
                               at /rustc/7bade6ef730cff83f3591479a98916920f66decd/library/std/src/panicking.rs:208:50
   9:     0x55a37d33f398 - std::panicking::default_hook::h3bc2efb48060abaa
                               at /rustc/7bade6ef730cff83f3591479a98916920f66decd/library/std/src/panicking.rs:227:9
  10:     0x55a37d33fdd1 - std::panicking::rust_panic_with_hook::h887eb0c89f46b8b2
                               at /rustc/7bade6ef730cff83f3591479a98916920f66decd/library/std/src/panicking.rs:577:17
  11:     0x55a37d33f979 - std::panicking::begin_panic_handler::{{closure}}::hf0d3f46d37dd3bc1
                               at /rustc/7bade6ef730cff83f3591479a98916920f66decd/library/std/src/panicking.rs:484:9
  12:     0x55a37d33d64c - std::sys_common::backtrace::__rust_end_short_backtrace::h4bce8b52717576e3
                               at /rustc/7bade6ef730cff83f3591479a98916920f66decd/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x55a37d33f939 - rust_begin_unwind
                               at /rustc/7bade6ef730cff83f3591479a98916920f66decd/library/std/src/panicking.rs:483:5
  14:     0x55a37d35c771 - core::panicking::panic_fmt::hb15d6f55e8472f62
                               at /rustc/7bade6ef730cff83f3591479a98916920f66decd/library/core/src/panicking.rs:85:14
  15:     0x55a37d35c6bd - core::panicking::panic::h5d1c61fed2502a5f
                               at /rustc/7bade6ef730cff83f3591479a98916920f66decd/library/core/src/panicking.rs:50:5
  16:     0x55a37d0fa6f1 - core::mem::uninitialized::he547514424cf8538
                               at /home/patrick/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/mem/mod.rs:659:9
  17:     0x55a37d0fa6f1 - winit::platform::platform::x11::util::input::<impl winit::platform::platform::x11::xdisplay::XConnection>::query_pointer::hd6ab35e229bbd170
                               at /home/patrick/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.19.5/src/platform/linux/x11/util/input.rs:94:51
  18:     0x55a37d076a26 - winit::platform::platform::x11::EventsLoop::process_event::he6d694f1322b88dd
                               at /home/patrick/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.19.5/src/platform/linux/x11/mod.rs:956:45
  19:     0x55a37d070b74 - winit::platform::platform::x11::EventsLoop::run_forever::h5cb6289a100604cb
                               at /home/patrick/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.19.5/src/platform/linux/x11/mod.rs:297:17
  20:     0x55a37d07e920 - winit::platform::platform::EventsLoop::run_forever::h4b54d28554167a75
                               at /home/patrick/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.19.5/src/platform/linux/mod.rs:531:44
  21:     0x55a37d082eee - winit::EventsLoop::run_forever::hb3c03c77a8b224cb
                               at /home/patrick/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.19.5/src/lib.rs:292:9
  22:     0x55a37d07e99e - winit_old::main::hf80432b2eb28c121
                               at /tmp/winit_old/src/main.rs:7:5
  23:     0x55a37d07ed0b - core::ops::function::FnOnce::call_once::h28d9c007836b6124
                               at /home/patrick/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
  24:     0x55a37d06e40e - std::sys_common::backtrace::__rust_begin_short_backtrace::hf4a68425d24b8d9f
                               at /home/patrick/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:125:18
  25:     0x55a37d06f511 - std::rt::lang_start::{{closure}}::hc9ca41098c2c9899
                               at /home/patrick/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/rt.rs:66:18
  26:     0x55a37d3401f7 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h1af42f2aaad601f7
                               at /rustc/7bade6ef730cff83f3591479a98916920f66decd/library/core/src/ops/function.rs:259:13
  27:     0x55a37d3401f7 - std::panicking::try::do_call::h9d43a73a8e9fb04a
                               at /rustc/7bade6ef730cff83f3591479a98916920f66decd/library/std/src/panicking.rs:381:40
  28:     0x55a37d3401f7 - std::panicking::try::h7a8d1100a6afe839
                               at /rustc/7bade6ef730cff83f3591479a98916920f66decd/library/std/src/panicking.rs:345:19
  29:     0x55a37d3401f7 - std::panic::catch_unwind::h9c80942da690cf03
                               at /rustc/7bade6ef730cff83f3591479a98916920f66decd/library/std/src/panic.rs:382:14
  30:     0x55a37d3401f7 - std::rt::lang_start_internal::h18ef240fb861b4d5
                               at /rustc/7bade6ef730cff83f3591479a98916920f66decd/library/std/src/rt.rs:51:25
  31:     0x55a37d06f4e7 - std::rt::lang_start::h61e5e9414e34b1a8
                               at /home/patrick/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/rt.rs:65:5
  32:     0x55a37d07ea3a - main
  33:     0x7f34b81a8152 - __libc_start_main
  34:     0x55a37d06b0be - _start
  35:                0x0 - <unknown>
```

**To Reproduce**
The `hello_world.rb` example works on stable Rust, but fails on nightly.

The error occurs inside `winit`, and can also be replicated by running the example from the `winit 0.19.1` README (the version ggez uses). It appears to be fixed in the latest `winit 0.23.0`, as its example runs fine on both stable and nightly.

**Expected behavior**
The panic does not occur.

**Hardware and Software:**
 - ggez version: 0.5.1
 - Non-working Rust version: nightly 1.49.0 (7bade6ef7 2020-10-23)
 - Working Rust version: stable 1.47.0 (f3c7e066a 2020-08-28)
 - OS: Linux (Arch Linux)
 - Graphics card: Intel Corporation Skylake GT2 [HD Graphics 520]

**Comment by icefoxen** [comment]
Thanks, looks like it's in winit and idk if they'll patch an old version but I'll take a look.  Could also in theory be a bug in nightly rustc, might want to take a look into that as well.

**Comment by Palladinium** [comment]
The current devel (`64c5fa6`) hits me with a few build errors, they look like winit functions whose names slightly changed. Pushed a PR to fix that.

With that fix in, it looks like it works, thank you!

Tested on nightly 1.49.0 (5404efc28 2020-11-11)

**Comment by icefoxen** [comment]
Great, thank you!
