### ISSUE TITLE
Sometimes switching screens in Linux will cause a panic

### ISSUE THREAD

**Issue by icefoxen** [ggez/ggez#9]
Seems to happen about 1/4 of the time on my laptop, very unreliable.  Doesn't *seem* to happen when the window is not selected.  

It's something weird happening in the timing code, but it's sort of weird.

Backtrace:
```
thread 'main' panicked at 'overflow when subtracting durations', ../src/libcore/option.rs:700
stack backtrace:
   1:     0x55810edb0519 - std::sys::backtrace::tracing::imp::write::h00e948915d1e4c72
   2:     0x55810edb3ebc - std::panicking::default_hook::_{{closure}}::h7b8a142818383fb8
   3:     0x55810edb31b9 - std::panicking::default_hook::h41cf296f654245d7
   4:     0x55810edb37f8 - std::panicking::rust_panic_with_hook::h4cbd7ca63ce1aee9
   5:     0x55810edb3652 - std::panicking::begin_panic::h93672d0313d5e8e9
   6:     0x55810edb35c0 - std::panicking::begin_panic_fmt::hd0daa02942245d81
   7:     0x55810edb3541 - rust_begin_unwind
   8:     0x55810edebc2f - core::panicking::panic_fmt::hbfc935564d134c1b
   9:     0x55810edebca5 - core::option::expect_failed::h1d846c7a667396f7
  10:     0x55810edae8bc - _<std..time..duration..Duration as core..ops..Sub>::sub::hedf4f5a7d9502bd0
  11:     0x55810ed3ba9f - ggez::timer::sleep_until_next_frame::h0c06a01155e5f08e
                        at /home/icefox/src/ggez/src/timer.rs:177
  12:     0x55810ecf5ea1 - _<astroblasto..MainState as ggez..game..GameState>::draw::h83e9d098d8960d6a
                        at /home/icefox/src/ggez/examples/astroblasto.rs:205
  13:     0x55810eceff1e - _<ggez..game..Game<'a, S>>::run::hd5b398ab82fbc6f6
                        at /home/icefox/src/ggez/src/game.rs:188
  14:     0x55810ecf6243 - astroblasto::main::h4882452e174ab6c4
                        at /home/icefox/src/ggez/examples/astroblasto.rs:247
  15:     0x55810edbb9a6 - __rust_maybe_catch_panic
  16:     0x55810edb2932 - std::rt::lang_start::h53bf99b0829cc03c
  17:     0x55810ecf69b3 - main
  18:     0x7fbe3d9f42b0 - __libc_start_main
  19:     0x55810eced119 - _start
  20:                0x0 - <unknown>
```

**Comment by icefoxen** [comment]
The code in question is this:
```.rust
pub fn sleep_until_next_frame(ctx: &Context, desired_fps: u32) {
    // We assume we'll never sleep more than a second!
    // Using an integer FPS target helps enforce this.
    assert!(desired_fps > 0);
    let tc = &ctx.timer_context;
    let fps_delay = 1.0 / (desired_fps as f64);
    let nanos_per_frame = fps_delay * 1e9;
    let duration_per_frame = time::Duration::new(0, nanos_per_frame as u32);
    let now = time::Instant::now();
    let time_spent_this_frame = now - tc.last_instant;
    let duration_to_sleep = duration_per_frame - time_spent_this_frame; // <=== UNDERFLOW HERE
    // println!("Sleeping for {:?}", duration_to_sleep);
    thread::sleep(duration_to_sleep);
}
```

So it looks like it freaks out if it takes longer to render a frame than it thinks any frame should take.

Score 1 for overflow/underflow checking by default.
